///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConstructButtons
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ConstructButtonsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("949b019f-16d6-4e05-84bb-2a0e2465bdb8")]
    public partial class ConstructButtonsRepository : RepoGenBaseFolder
    {
        static ConstructButtonsRepository instance = new ConstructButtonsRepository();
        ConstructButtonsRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        ConstructButtonsRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the ConstructButtonsRepository element repository.
        /// </summary>
        [RepositoryFolder("949b019f-16d6-4e05-84bb-2a0e2465bdb8")]
        public static ConstructButtonsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ConstructButtonsRepository() 
            : base("ConstructButtonsRepository", "/", null, 0, false, "949b019f-16d6-4e05-84bb-2a0e2465bdb8", ".\\RepositoryImages\\ConstructButtonsRepository949b019f.rximgres")
        {
            _snapxuntitled = new ConstructButtonsRepositoryFolders.SnapXUntitledAppFolder(this);
            _list1000 = new ConstructButtonsRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("949b019f-16d6-4e05-84bb-2a0e2465bdb8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("df197202-c3fb-4ce3-a56a-39ea2ce0172c")]
        public virtual ConstructButtonsRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("4d1580fd-cafb-4359-a656-ed636562d100")]
        public virtual ConstructButtonsRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class ConstructButtonsRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("df197202-c3fb-4ce3-a56a-39ea2ce0172c")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _featureswidthInfo;
            RepoItemInfo _diametricaltolerancezoneInfo;
            RepoItemInfo _radiobuttonidInfo;
            RepoItemInfo _radiobuttonlmcInfo;
            RepoItemInfo _radiobuttonmmcInfo;
            RepoItemInfo _radiobuttonodInfo;
            RepoItemInfo _radiobuttonrfsInfo;
            RepoItemInfo _valuewidthInfo;
            RepoItemInfo _featurestextwidthInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _featuresInfo;
            RepoItemInfo _datastreamInfo;
            RepoItemInfo _hideInfo;
            RepoItemInfo _skipInfo;
            RepoItemInfo _ansiInfo;
            RepoItemInfo _radiobuttonisoInfo;
            RepoItemInfo _nominaltextInfo;
            RepoItemInfo _uppertextInfo;
            RepoItemInfo _lowertextInfo;
            RepoItemInfo _positiontextInfo;
            RepoItemInfo _valueInfo;
            RepoItemInfo _featurestextInfo;
            RepoItemInfo _geometrictolerancetextInfo;
            RepoItemInfo _modifierstextInfo;
            RepoItemInfo _constructstepnameInfo;
            RepoItemInfo _dropdownbuttonInfo;
            RepoItemInfo _buttoncancelInfo;
            RepoItemInfo _features1Info;
            RepoItemInfo _reftextoneInfo;
            RepoItemInfo _circularitytextInfo;
            RepoItemInfo _concentricitytextInfo;
            RepoItemInfo _profiletextInfo;
            RepoItemInfo _diametercircleInfo;
            RepoItemInfo _radiuscircleInfo;
            RepoItemInfo _valuecircleInfo;
            RepoItemInfo _featurestextcircleInfo;
            RepoItemInfo _compositetextInfo;
            RepoItemInfo _features2Info;
            RepoItemInfo _dropdownbuttonlineoneInfo;
            RepoItemInfo _dropdownbuttonlinetwoInfo;
            RepoItemInfo _angletextInfo;
            RepoItemInfo _straightnesstextInfo;
            RepoItemInfo _parallelismtextInfo;
            RepoItemInfo _perpendicularitytextInfo;
            RepoItemInfo _angularitytextInfo;
            RepoItemInfo _reftexttwoInfo;
            RepoItemInfo _reftextthreeInfo;
            RepoItemInfo _valuelineInfo;
            RepoItemInfo _featurestextlineInfo;
            RepoItemInfo _features3Info;
            RepoItemInfo _locatepointInfo;
            RepoItemInfo _checkboxxInfo;
            RepoItemInfo _checkboxyInfo;
            RepoItemInfo _inputfromfileInfo;
            RepoItemInfo _keepfileInfo;
            RepoItemInfo _inputfromstepInfo;
            RepoItemInfo _valuepointInfo;
            RepoItemInfo _featurestextpointInfo;
            RepoItemInfo _atpostextmathInfo;
            RepoItemInfo _angularInfo;
            RepoItemInfo _linearInfo;
            RepoItemInfo _expressionInfo;
            RepoItemInfo _conditionsInfo;
            RepoItemInfo _gotosteptextbranchInfo;
            RepoItemInfo _thentextbranchInfo;
            RepoItemInfo _elsetextbranchInfo;
            RepoItemInfo _gotostepelsebranchInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "df197202-c3fb-4ce3-a56a-39ea2ce0172c", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "Titlebar", "titlebar[@accessiblerole='TitleBar']", 30000, null, "505d653a-f136-401d-a70f-a8a50f13c935");
                _featureswidthInfo = new RepoItemInfo(this, "FeaturesWidth", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/button[@controlid='1516' and @class='Button' and @instance='8']", 30000, null, "b082c264-94d2-498b-adf2-2e8c96c881ed");
                _diametricaltolerancezoneInfo = new RepoItemInfo(this, "DiametricalToleranceZone", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/checkbox[@text~'^Diametrical\\ tolerance\\ zon']", 30000, null, "241faead-582b-4d47-bd94-342953c9bfcf");
                _radiobuttonidInfo = new RepoItemInfo(this, "RadioButtonID", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/radiobutton[@text='ID']", 30000, null, "10b97af2-d148-4077-a367-24d0116d81a7");
                _radiobuttonlmcInfo = new RepoItemInfo(this, "RadioButtonLMC", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/radiobutton[@text='LMC']", 30000, null, "ecaaf612-58f7-41ea-ab75-cd71ddf88ef7");
                _radiobuttonmmcInfo = new RepoItemInfo(this, "RadioButtonMMC", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/radiobutton[@text='MMC']", 30000, null, "946047db-54de-4610-b3f2-c4ed8ec97dc6");
                _radiobuttonodInfo = new RepoItemInfo(this, "RadioButtonOD", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/radiobutton[@text='OD']", 30000, null, "9e5dae2f-af4b-4939-9501-cbb6ed74c0dd");
                _radiobuttonrfsInfo = new RepoItemInfo(this, "RadioButtonRFS", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/radiobutton[@text='RFS']", 30000, null, "3ca6069a-a0ad-4d36-9a28-6768fecb964a");
                _valuewidthInfo = new RepoItemInfo(this, "ValueWidth", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='0' and @class='Static' and @instance='17']", 30000, null, "629b89e7-96fe-405d-b67f-ad3d51245101");
                _featurestextwidthInfo = new RepoItemInfo(this, "FeaturesTextWidth", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='Features:' and @class='Static' and @instance='16']", 30000, null, "30c4fb29-b978-43bb-8c9f-31d37e819603");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[@controlid='59648']/form[@controlid='65281']//button[@text='&OK']", 30000, null, "e8170f2f-e4f9-4b03-88e9-96485689a29a");
                _featuresInfo = new RepoItemInfo(this, "Features", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/button[@controlid='1516' and @class='Button' and @instance='6']", 30000, null, "d2f9aaeb-b6c2-4e0b-9950-14784356b08f");
                _datastreamInfo = new RepoItemInfo(this, "DataStream", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/checkbox[@text='Data Stream']", 30000, null, "ddf9e664-80f1-4f47-b701-fbef3ae1c9ff");
                _hideInfo = new RepoItemInfo(this, "Hide", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/checkbox[@text='Hide']", 30000, null, "f62d51fa-8342-49e1-a6ca-d37387ca135f");
                _skipInfo = new RepoItemInfo(this, "Skip", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/checkbox[@text='Skip']", 30000, null, "710e9a7d-4446-41a8-a8f3-9162a9b1d3f0");
                _ansiInfo = new RepoItemInfo(this, "ANSI", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/radiobutton[@text='ANSI']", 30000, null, "ee86bb99-33f2-434a-9732-9874fecab013");
                _radiobuttonisoInfo = new RepoItemInfo(this, "RadioButtonISO", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/radiobutton[@text='ISO']", 30000, null, "13126ab4-edd2-4de3-89eb-f4072b24be58");
                _nominaltextInfo = new RepoItemInfo(this, "NominalText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1501']", 30000, null, "abdea130-da10-48d4-98bd-1ad886db0077");
                _uppertextInfo = new RepoItemInfo(this, "UpperText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1502']", 30000, null, "c5c00ea3-653d-4cba-b031-e407fd4ee63b");
                _lowertextInfo = new RepoItemInfo(this, "LowerText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1503']", 30000, null, "4d5f73e5-423c-4bf8-a62d-3e5f8447e1a7");
                _positiontextInfo = new RepoItemInfo(this, "PositionText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1512']", 30000, null, "b962f7c0-6a84-4db4-854c-5e8b8d00d0a9");
                _valueInfo = new RepoItemInfo(this, "Value", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='0' and @class='Static' and @instance='15']", 30000, null, "752f7e01-c9a3-431a-ace5-087b007b9cd4");
                _featurestextInfo = new RepoItemInfo(this, "FeaturesText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='Features:' and @class='Static' and @instance='14']", 30000, null, "dfecd940-d72f-4240-8873-9885868f6ac7");
                _geometrictolerancetextInfo = new RepoItemInfo(this, "GeometricToleranceText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='Geometric Tolerances']", 30000, null, "51ffa9a4-9a98-4af6-b3c3-f84f5976be6e");
                _modifierstextInfo = new RepoItemInfo(this, "ModifiersText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='Modifiers']", 30000, null, "8be51132-4270-480a-8154-a235c7966982");
                _constructstepnameInfo = new RepoItemInfo(this, "ConstructStepName", "container[@controlid='59648']/form[@controlid='65281']//text[@controlid='65535']", 30000, null, "43801666-d899-48d6-9ae4-61ef39a8b122");
                _dropdownbuttonInfo = new RepoItemInfo(this, "DropDownButton", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/combobox[@controlid='1151']/button[@text='>']", 30000, null, "4efacaa0-aa25-4b19-9361-a695349ecea3");
                _buttoncancelInfo = new RepoItemInfo(this, "ButtonCancel", "container[@controlid='59648']/form[@controlid='65281']//button[@controlid='33163']", 30000, null, "f8be19b5-a4f6-44df-8828-a56cb21011e7");
                _features1Info = new RepoItemInfo(this, "Features1", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/button[@controlid='1516' and @class='Button' and @instance='13']", 30000, null, "504b9c80-887a-4d56-8bb0-32af807e5cdf");
                _reftextoneInfo = new RepoItemInfo(this, "RefTextOne", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1218']", 30000, null, "d4287b12-b98b-46ce-8d4b-b477771d8c53");
                _circularitytextInfo = new RepoItemInfo(this, "CircularityText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1467']", 30000, null, "e42439f7-38a2-464d-871a-908cd23d1819");
                _concentricitytextInfo = new RepoItemInfo(this, "ConcentricityText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1510']", 30000, null, "11a92b92-d953-4e1e-8f56-cdb437a51a0d");
                _profiletextInfo = new RepoItemInfo(this, "ProfileText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1513']", 30000, null, "4df0ef70-7ea5-48ec-bee3-d808d5cd7dd1");
                _diametercircleInfo = new RepoItemInfo(this, "DiameterCircle", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/radiobutton[@text='Diameter']", 30000, null, "e6807605-f143-48fb-a3ad-ccc5276b40a1");
                _radiuscircleInfo = new RepoItemInfo(this, "RadiusCircle", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/radiobutton[@text='Radius']", 30000, null, "4a548262-49db-49da-9168-e88e6aa37a42");
                _valuecircleInfo = new RepoItemInfo(this, "ValueCircle", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='0' and @class='Static' and @instance='23']", 30000, null, "33812507-46c7-46b4-9617-d437777b6ba0");
                _featurestextcircleInfo = new RepoItemInfo(this, "FeaturesTextCircle", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='Features:' and @class='Static' and @instance='22']", 30000, null, "4b02a36d-72d7-4e2c-9615-322e9537473f");
                _compositetextInfo = new RepoItemInfo(this, "CompositeText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/checkbox[@text='Composite']", 30000, null, "430a06e6-5031-443a-ae4b-f19c1474aea5");
                _features2Info = new RepoItemInfo(this, "Features2", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/button[@controlid='1516' and @class='Button' and @instance='12']", 30000, null, "ed41b47a-2a2c-477c-a41c-1c2886c44cb9");
                _dropdownbuttonlineoneInfo = new RepoItemInfo(this, "DropDownButtonLineOne", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/combobox[@controlid='1163']/button[@text='>']", 30000, null, "73d37323-7a13-4961-b203-da71c4680a6d");
                _dropdownbuttonlinetwoInfo = new RepoItemInfo(this, "DropDownButtonLineTwo", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/combobox[@controlid='1169']/button[@text='>']", 30000, null, "0b26c48e-ac73-4c3f-9a68-c5ed8a5562f0");
                _angletextInfo = new RepoItemInfo(this, "AngleText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1240']", 30000, null, "14c494b2-6580-4745-8277-52c9eb09213a");
                _straightnesstextInfo = new RepoItemInfo(this, "StraightnessText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1485']", 30000, null, "f3ab2fab-9f44-49f6-8897-edc13efa04f0");
                _parallelismtextInfo = new RepoItemInfo(this, "ParallelismText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='1718']", 30000, null, "89d90781-3933-41b0-9dd2-0ef4e727e898");
                _perpendicularitytextInfo = new RepoItemInfo(this, "PerpendicularityText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='40133']", 30000, null, "dde280a6-1df0-4d18-924c-59914e437f8e");
                _angularitytextInfo = new RepoItemInfo(this, "AngularityText", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='40135']", 30000, null, "7ace81cb-68d5-4c25-aebe-4d1b5380220f");
                _reftexttwoInfo = new RepoItemInfo(this, "RefTextTwo", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='4121']", 30000, null, "e00fe1e8-d104-4c58-afad-c4d70ca755c5");
                _reftextthreeInfo = new RepoItemInfo(this, "RefTextThree", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/text[@controlid='4122']", 30000, null, "c2d258ae-19f9-4ea6-9018-c60f735fdfb6");
                _valuelineInfo = new RepoItemInfo(this, "ValueLine", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='0' and @class='Static' and @instance='25']", 30000, null, "eff76bcd-3ace-458d-9a15-b159cbb7138f");
                _featurestextlineInfo = new RepoItemInfo(this, "FeaturesTextLine", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='Features:' and @class='Static' and @instance='24']", 30000, null, "2c458267-722f-481b-a2e8-8321e902af44");
                _features3Info = new RepoItemInfo(this, "Features3", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/button[@controlid='1516' and @class='Button' and @instance='9']", 30000, null, "aebdfff9-da27-459e-b1dc-44f230052625");
                _locatepointInfo = new RepoItemInfo(this, "LocatePoint", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/checkbox[@text='Locate Point']", 30000, null, "4920f256-e398-45d2-b5d9-dc0b38e47330");
                _checkboxxInfo = new RepoItemInfo(this, "CheckBoxX", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/checkbox[@text='X']", 30000, null, "18381d0d-f87d-424a-9cc5-6e7d76e54019");
                _checkboxyInfo = new RepoItemInfo(this, "CheckBoxY", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/checkbox[@text='Y']", 30000, null, "88d1dad9-3f04-4351-b8b3-c80ba6475cb2");
                _inputfromfileInfo = new RepoItemInfo(this, "InputFromFile", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/checkbox[@text='Input From File']", 30000, null, "5cbaa640-9d08-49a5-be35-92d853c69325");
                _keepfileInfo = new RepoItemInfo(this, "KeepFile", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/checkbox[@text='Keep File']", 30000, null, "e5f6b3f3-ab53-4ad0-9375-8402d01acd19");
                _inputfromstepInfo = new RepoItemInfo(this, "InputFromStep", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@controlid='3001']/container[@accessiblename='Input From Step']", 30000, null, "cecae110-7689-4747-b8c1-0350cb17d01e");
                _valuepointInfo = new RepoItemInfo(this, "ValuePoint", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='0' and @class='Static' and @instance='13']", 30000, null, "c5bdbe0d-d706-4c5c-8b98-d6d0c213c366");
                _featurestextpointInfo = new RepoItemInfo(this, "FeaturesTextPoint", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@caption='Features:' and @class='Static' and @instance='12']", 30000, null, "90205f9c-71e5-4cd1-9991-da96496f7c25");
                _atpostextmathInfo = new RepoItemInfo(this, "AtPosTextMath", "container[@controlid='59648']/form[@controlid='65281']//text[@controlid='33170']", 30000, null, "987b9fdc-f2f2-4971-8d12-812a8bebb7a5");
                _angularInfo = new RepoItemInfo(this, "Angular", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/radiobutton[@text='Angular']", 30000, null, "f5b88d30-368e-45b9-934d-80f28a7da4bf");
                _linearInfo = new RepoItemInfo(this, "Linear", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@class='#32770']/radiobutton[@text='Linear']", 30000, null, "188fbd95-2105-4e81-b9d2-675a4efe522b");
                _expressionInfo = new RepoItemInfo(this, "Expression", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@controlid='1506']/container[@accessiblename='Expression:']", 30000, null, "38ed6664-3127-4f8f-991f-446309e2cde4");
                _conditionsInfo = new RepoItemInfo(this, "Conditions", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/container[@controlid='1497']/container[@accessiblename='Conditions']", 30000, null, "cdf0856d-f429-4a4d-86ab-9bcd1d5c526a");
                _gotosteptextbranchInfo = new RepoItemInfo(this, "GoToStepTextBranch", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@controlid='1502']", 30000, null, "7d2cf70c-9bd5-4b71-81ee-0d15a3175290");
                _thentextbranchInfo = new RepoItemInfo(this, "THENTextBranch", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@controlid='1859']", 30000, null, "be5989c9-9ca1-4acc-a6e2-3738e7e1f96a");
                _elsetextbranchInfo = new RepoItemInfo(this, "ELSETextBranch", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@controlid='1860']", 30000, null, "82706444-6c12-4b3e-b5fe-11b0520e39f2");
                _gotostepelsebranchInfo = new RepoItemInfo(this, "GoToStepElseBranch", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']/?/?/text[@controlid='1861']", 30000, null, "9f118903-be1f-4657-88ad-a6c01a4004cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df197202-c3fb-4ce3-a56a-39ea2ce0172c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df197202-c3fb-4ce3-a56a-39ea2ce0172c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Titlebar item.
            /// </summary>
            [RepositoryItem("505d653a-f136-401d-a70f-a8a50f13c935")]
            public virtual Ranorex.TitleBar Titlebar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The Titlebar item info.
            /// </summary>
            [RepositoryItemInfo("505d653a-f136-401d-a70f-a8a50f13c935")]
            public virtual RepoItemInfo TitlebarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The FeaturesWidth item.
            /// </summary>
            [RepositoryItem("b082c264-94d2-498b-adf2-2e8c96c881ed")]
            public virtual Ranorex.Button FeaturesWidth
            {
                get
                {
                    return _featureswidthInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FeaturesWidth item info.
            /// </summary>
            [RepositoryItemInfo("b082c264-94d2-498b-adf2-2e8c96c881ed")]
            public virtual RepoItemInfo FeaturesWidthInfo
            {
                get
                {
                    return _featureswidthInfo;
                }
            }

            /// <summary>
            /// The DiametricalToleranceZone item.
            /// </summary>
            [RepositoryItem("241faead-582b-4d47-bd94-342953c9bfcf")]
            public virtual Ranorex.CheckBox DiametricalToleranceZone
            {
                get
                {
                    return _diametricaltolerancezoneInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The DiametricalToleranceZone item info.
            /// </summary>
            [RepositoryItemInfo("241faead-582b-4d47-bd94-342953c9bfcf")]
            public virtual RepoItemInfo DiametricalToleranceZoneInfo
            {
                get
                {
                    return _diametricaltolerancezoneInfo;
                }
            }

            /// <summary>
            /// The RadioButtonID item.
            /// </summary>
            [RepositoryItem("10b97af2-d148-4077-a367-24d0116d81a7")]
            public virtual Ranorex.RadioButton RadioButtonID
            {
                get
                {
                    return _radiobuttonidInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonID item info.
            /// </summary>
            [RepositoryItemInfo("10b97af2-d148-4077-a367-24d0116d81a7")]
            public virtual RepoItemInfo RadioButtonIDInfo
            {
                get
                {
                    return _radiobuttonidInfo;
                }
            }

            /// <summary>
            /// The RadioButtonLMC item.
            /// </summary>
            [RepositoryItem("ecaaf612-58f7-41ea-ab75-cd71ddf88ef7")]
            public virtual Ranorex.RadioButton RadioButtonLMC
            {
                get
                {
                    return _radiobuttonlmcInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonLMC item info.
            /// </summary>
            [RepositoryItemInfo("ecaaf612-58f7-41ea-ab75-cd71ddf88ef7")]
            public virtual RepoItemInfo RadioButtonLMCInfo
            {
                get
                {
                    return _radiobuttonlmcInfo;
                }
            }

            /// <summary>
            /// The RadioButtonMMC item.
            /// </summary>
            [RepositoryItem("946047db-54de-4610-b3f2-c4ed8ec97dc6")]
            public virtual Ranorex.RadioButton RadioButtonMMC
            {
                get
                {
                    return _radiobuttonmmcInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonMMC item info.
            /// </summary>
            [RepositoryItemInfo("946047db-54de-4610-b3f2-c4ed8ec97dc6")]
            public virtual RepoItemInfo RadioButtonMMCInfo
            {
                get
                {
                    return _radiobuttonmmcInfo;
                }
            }

            /// <summary>
            /// The RadioButtonOD item.
            /// </summary>
            [RepositoryItem("9e5dae2f-af4b-4939-9501-cbb6ed74c0dd")]
            public virtual Ranorex.RadioButton RadioButtonOD
            {
                get
                {
                    return _radiobuttonodInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonOD item info.
            /// </summary>
            [RepositoryItemInfo("9e5dae2f-af4b-4939-9501-cbb6ed74c0dd")]
            public virtual RepoItemInfo RadioButtonODInfo
            {
                get
                {
                    return _radiobuttonodInfo;
                }
            }

            /// <summary>
            /// The RadioButtonRFS item.
            /// </summary>
            [RepositoryItem("3ca6069a-a0ad-4d36-9a28-6768fecb964a")]
            public virtual Ranorex.RadioButton RadioButtonRFS
            {
                get
                {
                    return _radiobuttonrfsInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonRFS item info.
            /// </summary>
            [RepositoryItemInfo("3ca6069a-a0ad-4d36-9a28-6768fecb964a")]
            public virtual RepoItemInfo RadioButtonRFSInfo
            {
                get
                {
                    return _radiobuttonrfsInfo;
                }
            }

            /// <summary>
            /// The ValueWidth item.
            /// </summary>
            [RepositoryItem("629b89e7-96fe-405d-b67f-ad3d51245101")]
            public virtual Ranorex.Text ValueWidth
            {
                get
                {
                    return _valuewidthInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ValueWidth item info.
            /// </summary>
            [RepositoryItemInfo("629b89e7-96fe-405d-b67f-ad3d51245101")]
            public virtual RepoItemInfo ValueWidthInfo
            {
                get
                {
                    return _valuewidthInfo;
                }
            }

            /// <summary>
            /// The FeaturesTextWidth item.
            /// </summary>
            [RepositoryItem("30c4fb29-b978-43bb-8c9f-31d37e819603")]
            public virtual Ranorex.Text FeaturesTextWidth
            {
                get
                {
                    return _featurestextwidthInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FeaturesTextWidth item info.
            /// </summary>
            [RepositoryItemInfo("30c4fb29-b978-43bb-8c9f-31d37e819603")]
            public virtual RepoItemInfo FeaturesTextWidthInfo
            {
                get
                {
                    return _featurestextwidthInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("e8170f2f-e4f9-4b03-88e9-96485689a29a")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("e8170f2f-e4f9-4b03-88e9-96485689a29a")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Features item.
            /// </summary>
            [RepositoryItem("d2f9aaeb-b6c2-4e0b-9950-14784356b08f")]
            public virtual Ranorex.Button Features
            {
                get
                {
                    return _featuresInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Features item info.
            /// </summary>
            [RepositoryItemInfo("d2f9aaeb-b6c2-4e0b-9950-14784356b08f")]
            public virtual RepoItemInfo FeaturesInfo
            {
                get
                {
                    return _featuresInfo;
                }
            }

            /// <summary>
            /// The DataStream item.
            /// </summary>
            [RepositoryItem("ddf9e664-80f1-4f47-b701-fbef3ae1c9ff")]
            public virtual Ranorex.CheckBox DataStream
            {
                get
                {
                    return _datastreamInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The DataStream item info.
            /// </summary>
            [RepositoryItemInfo("ddf9e664-80f1-4f47-b701-fbef3ae1c9ff")]
            public virtual RepoItemInfo DataStreamInfo
            {
                get
                {
                    return _datastreamInfo;
                }
            }

            /// <summary>
            /// The Hide item.
            /// </summary>
            [RepositoryItem("f62d51fa-8342-49e1-a6ca-d37387ca135f")]
            public virtual Ranorex.CheckBox Hide
            {
                get
                {
                    return _hideInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The Hide item info.
            /// </summary>
            [RepositoryItemInfo("f62d51fa-8342-49e1-a6ca-d37387ca135f")]
            public virtual RepoItemInfo HideInfo
            {
                get
                {
                    return _hideInfo;
                }
            }

            /// <summary>
            /// The Skip item.
            /// </summary>
            [RepositoryItem("710e9a7d-4446-41a8-a8f3-9162a9b1d3f0")]
            public virtual Ranorex.CheckBox Skip
            {
                get
                {
                    return _skipInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The Skip item info.
            /// </summary>
            [RepositoryItemInfo("710e9a7d-4446-41a8-a8f3-9162a9b1d3f0")]
            public virtual RepoItemInfo SkipInfo
            {
                get
                {
                    return _skipInfo;
                }
            }

            /// <summary>
            /// The ANSI item.
            /// </summary>
            [RepositoryItem("ee86bb99-33f2-434a-9732-9874fecab013")]
            public virtual Ranorex.RadioButton ANSI
            {
                get
                {
                    return _ansiInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The ANSI item info.
            /// </summary>
            [RepositoryItemInfo("ee86bb99-33f2-434a-9732-9874fecab013")]
            public virtual RepoItemInfo ANSIInfo
            {
                get
                {
                    return _ansiInfo;
                }
            }

            /// <summary>
            /// The RadioButtonISO item.
            /// </summary>
            [RepositoryItem("13126ab4-edd2-4de3-89eb-f4072b24be58")]
            public virtual Ranorex.RadioButton RadioButtonISO
            {
                get
                {
                    return _radiobuttonisoInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonISO item info.
            /// </summary>
            [RepositoryItemInfo("13126ab4-edd2-4de3-89eb-f4072b24be58")]
            public virtual RepoItemInfo RadioButtonISOInfo
            {
                get
                {
                    return _radiobuttonisoInfo;
                }
            }

            /// <summary>
            /// The NominalText item.
            /// </summary>
            [RepositoryItem("abdea130-da10-48d4-98bd-1ad886db0077")]
            public virtual Ranorex.Text NominalText
            {
                get
                {
                    return _nominaltextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NominalText item info.
            /// </summary>
            [RepositoryItemInfo("abdea130-da10-48d4-98bd-1ad886db0077")]
            public virtual RepoItemInfo NominalTextInfo
            {
                get
                {
                    return _nominaltextInfo;
                }
            }

            /// <summary>
            /// The UpperText item.
            /// </summary>
            [RepositoryItem("c5c00ea3-653d-4cba-b031-e407fd4ee63b")]
            public virtual Ranorex.Text UpperText
            {
                get
                {
                    return _uppertextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpperText item info.
            /// </summary>
            [RepositoryItemInfo("c5c00ea3-653d-4cba-b031-e407fd4ee63b")]
            public virtual RepoItemInfo UpperTextInfo
            {
                get
                {
                    return _uppertextInfo;
                }
            }

            /// <summary>
            /// The LowerText item.
            /// </summary>
            [RepositoryItem("4d5f73e5-423c-4bf8-a62d-3e5f8447e1a7")]
            public virtual Ranorex.Text LowerText
            {
                get
                {
                    return _lowertextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LowerText item info.
            /// </summary>
            [RepositoryItemInfo("4d5f73e5-423c-4bf8-a62d-3e5f8447e1a7")]
            public virtual RepoItemInfo LowerTextInfo
            {
                get
                {
                    return _lowertextInfo;
                }
            }

            /// <summary>
            /// The PositionText item.
            /// </summary>
            [RepositoryItem("b962f7c0-6a84-4db4-854c-5e8b8d00d0a9")]
            public virtual Ranorex.Text PositionText
            {
                get
                {
                    return _positiontextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PositionText item info.
            /// </summary>
            [RepositoryItemInfo("b962f7c0-6a84-4db4-854c-5e8b8d00d0a9")]
            public virtual RepoItemInfo PositionTextInfo
            {
                get
                {
                    return _positiontextInfo;
                }
            }

            /// <summary>
            /// The Value item.
            /// </summary>
            [RepositoryItem("752f7e01-c9a3-431a-ace5-087b007b9cd4")]
            public virtual Ranorex.Text Value
            {
                get
                {
                    return _valueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Value item info.
            /// </summary>
            [RepositoryItemInfo("752f7e01-c9a3-431a-ace5-087b007b9cd4")]
            public virtual RepoItemInfo ValueInfo
            {
                get
                {
                    return _valueInfo;
                }
            }

            /// <summary>
            /// The FeaturesText item.
            /// </summary>
            [RepositoryItem("dfecd940-d72f-4240-8873-9885868f6ac7")]
            public virtual Ranorex.Text FeaturesText
            {
                get
                {
                    return _featurestextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FeaturesText item info.
            /// </summary>
            [RepositoryItemInfo("dfecd940-d72f-4240-8873-9885868f6ac7")]
            public virtual RepoItemInfo FeaturesTextInfo
            {
                get
                {
                    return _featurestextInfo;
                }
            }

            /// <summary>
            /// The GeometricToleranceText item.
            /// </summary>
            [RepositoryItem("51ffa9a4-9a98-4af6-b3c3-f84f5976be6e")]
            public virtual Ranorex.Text GeometricToleranceText
            {
                get
                {
                    return _geometrictolerancetextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GeometricToleranceText item info.
            /// </summary>
            [RepositoryItemInfo("51ffa9a4-9a98-4af6-b3c3-f84f5976be6e")]
            public virtual RepoItemInfo GeometricToleranceTextInfo
            {
                get
                {
                    return _geometrictolerancetextInfo;
                }
            }

            /// <summary>
            /// The ModifiersText item.
            /// </summary>
            [RepositoryItem("8be51132-4270-480a-8154-a235c7966982")]
            public virtual Ranorex.Text ModifiersText
            {
                get
                {
                    return _modifierstextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ModifiersText item info.
            /// </summary>
            [RepositoryItemInfo("8be51132-4270-480a-8154-a235c7966982")]
            public virtual RepoItemInfo ModifiersTextInfo
            {
                get
                {
                    return _modifierstextInfo;
                }
            }

            /// <summary>
            /// The ConstructStepName item.
            /// </summary>
            [RepositoryItem("43801666-d899-48d6-9ae4-61ef39a8b122")]
            public virtual Ranorex.Text ConstructStepName
            {
                get
                {
                    return _constructstepnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ConstructStepName item info.
            /// </summary>
            [RepositoryItemInfo("43801666-d899-48d6-9ae4-61ef39a8b122")]
            public virtual RepoItemInfo ConstructStepNameInfo
            {
                get
                {
                    return _constructstepnameInfo;
                }
            }

            /// <summary>
            /// The DropDownButton item.
            /// </summary>
            [RepositoryItem("4efacaa0-aa25-4b19-9361-a695349ecea3")]
            public virtual Ranorex.Button DropDownButton
            {
                get
                {
                    return _dropdownbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DropDownButton item info.
            /// </summary>
            [RepositoryItemInfo("4efacaa0-aa25-4b19-9361-a695349ecea3")]
            public virtual RepoItemInfo DropDownButtonInfo
            {
                get
                {
                    return _dropdownbuttonInfo;
                }
            }

            /// <summary>
            /// The ButtonCancel item.
            /// </summary>
            [RepositoryItem("f8be19b5-a4f6-44df-8828-a56cb21011e7")]
            public virtual Ranorex.Button ButtonCancel
            {
                get
                {
                    return _buttoncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonCancel item info.
            /// </summary>
            [RepositoryItemInfo("f8be19b5-a4f6-44df-8828-a56cb21011e7")]
            public virtual RepoItemInfo ButtonCancelInfo
            {
                get
                {
                    return _buttoncancelInfo;
                }
            }

            /// <summary>
            /// The Features1 item.
            /// </summary>
            [RepositoryItem("504b9c80-887a-4d56-8bb0-32af807e5cdf")]
            public virtual Ranorex.Button Features1
            {
                get
                {
                    return _features1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Features1 item info.
            /// </summary>
            [RepositoryItemInfo("504b9c80-887a-4d56-8bb0-32af807e5cdf")]
            public virtual RepoItemInfo Features1Info
            {
                get
                {
                    return _features1Info;
                }
            }

            /// <summary>
            /// The RefTextOne item.
            /// </summary>
            [RepositoryItem("d4287b12-b98b-46ce-8d4b-b477771d8c53")]
            public virtual Ranorex.Text RefTextOne
            {
                get
                {
                    return _reftextoneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RefTextOne item info.
            /// </summary>
            [RepositoryItemInfo("d4287b12-b98b-46ce-8d4b-b477771d8c53")]
            public virtual RepoItemInfo RefTextOneInfo
            {
                get
                {
                    return _reftextoneInfo;
                }
            }

            /// <summary>
            /// The CircularityText item.
            /// </summary>
            [RepositoryItem("e42439f7-38a2-464d-871a-908cd23d1819")]
            public virtual Ranorex.Text CircularityText
            {
                get
                {
                    return _circularitytextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CircularityText item info.
            /// </summary>
            [RepositoryItemInfo("e42439f7-38a2-464d-871a-908cd23d1819")]
            public virtual RepoItemInfo CircularityTextInfo
            {
                get
                {
                    return _circularitytextInfo;
                }
            }

            /// <summary>
            /// The ConcentricityText item.
            /// </summary>
            [RepositoryItem("11a92b92-d953-4e1e-8f56-cdb437a51a0d")]
            public virtual Ranorex.Text ConcentricityText
            {
                get
                {
                    return _concentricitytextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ConcentricityText item info.
            /// </summary>
            [RepositoryItemInfo("11a92b92-d953-4e1e-8f56-cdb437a51a0d")]
            public virtual RepoItemInfo ConcentricityTextInfo
            {
                get
                {
                    return _concentricitytextInfo;
                }
            }

            /// <summary>
            /// The ProfileText item.
            /// </summary>
            [RepositoryItem("4df0ef70-7ea5-48ec-bee3-d808d5cd7dd1")]
            public virtual Ranorex.Text ProfileText
            {
                get
                {
                    return _profiletextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ProfileText item info.
            /// </summary>
            [RepositoryItemInfo("4df0ef70-7ea5-48ec-bee3-d808d5cd7dd1")]
            public virtual RepoItemInfo ProfileTextInfo
            {
                get
                {
                    return _profiletextInfo;
                }
            }

            /// <summary>
            /// The DiameterCircle item.
            /// </summary>
            [RepositoryItem("e6807605-f143-48fb-a3ad-ccc5276b40a1")]
            public virtual Ranorex.RadioButton DiameterCircle
            {
                get
                {
                    return _diametercircleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The DiameterCircle item info.
            /// </summary>
            [RepositoryItemInfo("e6807605-f143-48fb-a3ad-ccc5276b40a1")]
            public virtual RepoItemInfo DiameterCircleInfo
            {
                get
                {
                    return _diametercircleInfo;
                }
            }

            /// <summary>
            /// The RadiusCircle item.
            /// </summary>
            [RepositoryItem("4a548262-49db-49da-9168-e88e6aa37a42")]
            public virtual Ranorex.RadioButton RadiusCircle
            {
                get
                {
                    return _radiuscircleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadiusCircle item info.
            /// </summary>
            [RepositoryItemInfo("4a548262-49db-49da-9168-e88e6aa37a42")]
            public virtual RepoItemInfo RadiusCircleInfo
            {
                get
                {
                    return _radiuscircleInfo;
                }
            }

            /// <summary>
            /// The ValueCircle item.
            /// </summary>
            [RepositoryItem("33812507-46c7-46b4-9617-d437777b6ba0")]
            public virtual Ranorex.Text ValueCircle
            {
                get
                {
                    return _valuecircleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ValueCircle item info.
            /// </summary>
            [RepositoryItemInfo("33812507-46c7-46b4-9617-d437777b6ba0")]
            public virtual RepoItemInfo ValueCircleInfo
            {
                get
                {
                    return _valuecircleInfo;
                }
            }

            /// <summary>
            /// The FeaturesTextCircle item.
            /// </summary>
            [RepositoryItem("4b02a36d-72d7-4e2c-9615-322e9537473f")]
            public virtual Ranorex.Text FeaturesTextCircle
            {
                get
                {
                    return _featurestextcircleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FeaturesTextCircle item info.
            /// </summary>
            [RepositoryItemInfo("4b02a36d-72d7-4e2c-9615-322e9537473f")]
            public virtual RepoItemInfo FeaturesTextCircleInfo
            {
                get
                {
                    return _featurestextcircleInfo;
                }
            }

            /// <summary>
            /// The CompositeText item.
            /// </summary>
            [RepositoryItem("430a06e6-5031-443a-ae4b-f19c1474aea5")]
            public virtual Ranorex.CheckBox CompositeText
            {
                get
                {
                    return _compositetextInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CompositeText item info.
            /// </summary>
            [RepositoryItemInfo("430a06e6-5031-443a-ae4b-f19c1474aea5")]
            public virtual RepoItemInfo CompositeTextInfo
            {
                get
                {
                    return _compositetextInfo;
                }
            }

            /// <summary>
            /// The Features2 item.
            /// </summary>
            [RepositoryItem("ed41b47a-2a2c-477c-a41c-1c2886c44cb9")]
            public virtual Ranorex.Button Features2
            {
                get
                {
                    return _features2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Features2 item info.
            /// </summary>
            [RepositoryItemInfo("ed41b47a-2a2c-477c-a41c-1c2886c44cb9")]
            public virtual RepoItemInfo Features2Info
            {
                get
                {
                    return _features2Info;
                }
            }

            /// <summary>
            /// The DropDownButtonLineOne item.
            /// </summary>
            [RepositoryItem("73d37323-7a13-4961-b203-da71c4680a6d")]
            public virtual Ranorex.Button DropDownButtonLineOne
            {
                get
                {
                    return _dropdownbuttonlineoneInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DropDownButtonLineOne item info.
            /// </summary>
            [RepositoryItemInfo("73d37323-7a13-4961-b203-da71c4680a6d")]
            public virtual RepoItemInfo DropDownButtonLineOneInfo
            {
                get
                {
                    return _dropdownbuttonlineoneInfo;
                }
            }

            /// <summary>
            /// The DropDownButtonLineTwo item.
            /// </summary>
            [RepositoryItem("0b26c48e-ac73-4c3f-9a68-c5ed8a5562f0")]
            public virtual Ranorex.Button DropDownButtonLineTwo
            {
                get
                {
                    return _dropdownbuttonlinetwoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DropDownButtonLineTwo item info.
            /// </summary>
            [RepositoryItemInfo("0b26c48e-ac73-4c3f-9a68-c5ed8a5562f0")]
            public virtual RepoItemInfo DropDownButtonLineTwoInfo
            {
                get
                {
                    return _dropdownbuttonlinetwoInfo;
                }
            }

            /// <summary>
            /// The AngleText item.
            /// </summary>
            [RepositoryItem("14c494b2-6580-4745-8277-52c9eb09213a")]
            public virtual Ranorex.Text AngleText
            {
                get
                {
                    return _angletextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AngleText item info.
            /// </summary>
            [RepositoryItemInfo("14c494b2-6580-4745-8277-52c9eb09213a")]
            public virtual RepoItemInfo AngleTextInfo
            {
                get
                {
                    return _angletextInfo;
                }
            }

            /// <summary>
            /// The StraightnessText item.
            /// </summary>
            [RepositoryItem("f3ab2fab-9f44-49f6-8897-edc13efa04f0")]
            public virtual Ranorex.Text StraightnessText
            {
                get
                {
                    return _straightnesstextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StraightnessText item info.
            /// </summary>
            [RepositoryItemInfo("f3ab2fab-9f44-49f6-8897-edc13efa04f0")]
            public virtual RepoItemInfo StraightnessTextInfo
            {
                get
                {
                    return _straightnesstextInfo;
                }
            }

            /// <summary>
            /// The ParallelismText item.
            /// </summary>
            [RepositoryItem("89d90781-3933-41b0-9dd2-0ef4e727e898")]
            public virtual Ranorex.Text ParallelismText
            {
                get
                {
                    return _parallelismtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ParallelismText item info.
            /// </summary>
            [RepositoryItemInfo("89d90781-3933-41b0-9dd2-0ef4e727e898")]
            public virtual RepoItemInfo ParallelismTextInfo
            {
                get
                {
                    return _parallelismtextInfo;
                }
            }

            /// <summary>
            /// The PerpendicularityText item.
            /// </summary>
            [RepositoryItem("dde280a6-1df0-4d18-924c-59914e437f8e")]
            public virtual Ranorex.Text PerpendicularityText
            {
                get
                {
                    return _perpendicularitytextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PerpendicularityText item info.
            /// </summary>
            [RepositoryItemInfo("dde280a6-1df0-4d18-924c-59914e437f8e")]
            public virtual RepoItemInfo PerpendicularityTextInfo
            {
                get
                {
                    return _perpendicularitytextInfo;
                }
            }

            /// <summary>
            /// The AngularityText item.
            /// </summary>
            [RepositoryItem("7ace81cb-68d5-4c25-aebe-4d1b5380220f")]
            public virtual Ranorex.Text AngularityText
            {
                get
                {
                    return _angularitytextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AngularityText item info.
            /// </summary>
            [RepositoryItemInfo("7ace81cb-68d5-4c25-aebe-4d1b5380220f")]
            public virtual RepoItemInfo AngularityTextInfo
            {
                get
                {
                    return _angularitytextInfo;
                }
            }

            /// <summary>
            /// The RefTextTwo item.
            /// </summary>
            [RepositoryItem("e00fe1e8-d104-4c58-afad-c4d70ca755c5")]
            public virtual Ranorex.Text RefTextTwo
            {
                get
                {
                    return _reftexttwoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RefTextTwo item info.
            /// </summary>
            [RepositoryItemInfo("e00fe1e8-d104-4c58-afad-c4d70ca755c5")]
            public virtual RepoItemInfo RefTextTwoInfo
            {
                get
                {
                    return _reftexttwoInfo;
                }
            }

            /// <summary>
            /// The RefTextThree item.
            /// </summary>
            [RepositoryItem("c2d258ae-19f9-4ea6-9018-c60f735fdfb6")]
            public virtual Ranorex.Text RefTextThree
            {
                get
                {
                    return _reftextthreeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RefTextThree item info.
            /// </summary>
            [RepositoryItemInfo("c2d258ae-19f9-4ea6-9018-c60f735fdfb6")]
            public virtual RepoItemInfo RefTextThreeInfo
            {
                get
                {
                    return _reftextthreeInfo;
                }
            }

            /// <summary>
            /// The ValueLine item.
            /// </summary>
            [RepositoryItem("eff76bcd-3ace-458d-9a15-b159cbb7138f")]
            public virtual Ranorex.Text ValueLine
            {
                get
                {
                    return _valuelineInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ValueLine item info.
            /// </summary>
            [RepositoryItemInfo("eff76bcd-3ace-458d-9a15-b159cbb7138f")]
            public virtual RepoItemInfo ValueLineInfo
            {
                get
                {
                    return _valuelineInfo;
                }
            }

            /// <summary>
            /// The FeaturesTextLine item.
            /// </summary>
            [RepositoryItem("2c458267-722f-481b-a2e8-8321e902af44")]
            public virtual Ranorex.Text FeaturesTextLine
            {
                get
                {
                    return _featurestextlineInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FeaturesTextLine item info.
            /// </summary>
            [RepositoryItemInfo("2c458267-722f-481b-a2e8-8321e902af44")]
            public virtual RepoItemInfo FeaturesTextLineInfo
            {
                get
                {
                    return _featurestextlineInfo;
                }
            }

            /// <summary>
            /// The Features3 item.
            /// </summary>
            [RepositoryItem("aebdfff9-da27-459e-b1dc-44f230052625")]
            public virtual Ranorex.Button Features3
            {
                get
                {
                    return _features3Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Features3 item info.
            /// </summary>
            [RepositoryItemInfo("aebdfff9-da27-459e-b1dc-44f230052625")]
            public virtual RepoItemInfo Features3Info
            {
                get
                {
                    return _features3Info;
                }
            }

            /// <summary>
            /// The LocatePoint item.
            /// </summary>
            [RepositoryItem("4920f256-e398-45d2-b5d9-dc0b38e47330")]
            public virtual Ranorex.CheckBox LocatePoint
            {
                get
                {
                    return _locatepointInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The LocatePoint item info.
            /// </summary>
            [RepositoryItemInfo("4920f256-e398-45d2-b5d9-dc0b38e47330")]
            public virtual RepoItemInfo LocatePointInfo
            {
                get
                {
                    return _locatepointInfo;
                }
            }

            /// <summary>
            /// The CheckBoxX item.
            /// </summary>
            [RepositoryItem("18381d0d-f87d-424a-9cc5-6e7d76e54019")]
            public virtual Ranorex.CheckBox CheckBoxX
            {
                get
                {
                    return _checkboxxInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBoxX item info.
            /// </summary>
            [RepositoryItemInfo("18381d0d-f87d-424a-9cc5-6e7d76e54019")]
            public virtual RepoItemInfo CheckBoxXInfo
            {
                get
                {
                    return _checkboxxInfo;
                }
            }

            /// <summary>
            /// The CheckBoxY item.
            /// </summary>
            [RepositoryItem("88d1dad9-3f04-4351-b8b3-c80ba6475cb2")]
            public virtual Ranorex.CheckBox CheckBoxY
            {
                get
                {
                    return _checkboxyInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBoxY item info.
            /// </summary>
            [RepositoryItemInfo("88d1dad9-3f04-4351-b8b3-c80ba6475cb2")]
            public virtual RepoItemInfo CheckBoxYInfo
            {
                get
                {
                    return _checkboxyInfo;
                }
            }

            /// <summary>
            /// The InputFromFile item.
            /// </summary>
            [RepositoryItem("5cbaa640-9d08-49a5-be35-92d853c69325")]
            public virtual Ranorex.CheckBox InputFromFile
            {
                get
                {
                    return _inputfromfileInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The InputFromFile item info.
            /// </summary>
            [RepositoryItemInfo("5cbaa640-9d08-49a5-be35-92d853c69325")]
            public virtual RepoItemInfo InputFromFileInfo
            {
                get
                {
                    return _inputfromfileInfo;
                }
            }

            /// <summary>
            /// The KeepFile item.
            /// </summary>
            [RepositoryItem("e5f6b3f3-ab53-4ad0-9375-8402d01acd19")]
            public virtual Ranorex.CheckBox KeepFile
            {
                get
                {
                    return _keepfileInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The KeepFile item info.
            /// </summary>
            [RepositoryItemInfo("e5f6b3f3-ab53-4ad0-9375-8402d01acd19")]
            public virtual RepoItemInfo KeepFileInfo
            {
                get
                {
                    return _keepfileInfo;
                }
            }

            /// <summary>
            /// The InputFromStep item.
            /// </summary>
            [RepositoryItem("cecae110-7689-4747-b8c1-0350cb17d01e")]
            public virtual Ranorex.Container InputFromStep
            {
                get
                {
                    return _inputfromstepInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The InputFromStep item info.
            /// </summary>
            [RepositoryItemInfo("cecae110-7689-4747-b8c1-0350cb17d01e")]
            public virtual RepoItemInfo InputFromStepInfo
            {
                get
                {
                    return _inputfromstepInfo;
                }
            }

            /// <summary>
            /// The ValuePoint item.
            /// </summary>
            [RepositoryItem("c5bdbe0d-d706-4c5c-8b98-d6d0c213c366")]
            public virtual Ranorex.Text ValuePoint
            {
                get
                {
                    return _valuepointInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ValuePoint item info.
            /// </summary>
            [RepositoryItemInfo("c5bdbe0d-d706-4c5c-8b98-d6d0c213c366")]
            public virtual RepoItemInfo ValuePointInfo
            {
                get
                {
                    return _valuepointInfo;
                }
            }

            /// <summary>
            /// The FeaturesTextPoint item.
            /// </summary>
            [RepositoryItem("90205f9c-71e5-4cd1-9991-da96496f7c25")]
            public virtual Ranorex.Text FeaturesTextPoint
            {
                get
                {
                    return _featurestextpointInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FeaturesTextPoint item info.
            /// </summary>
            [RepositoryItemInfo("90205f9c-71e5-4cd1-9991-da96496f7c25")]
            public virtual RepoItemInfo FeaturesTextPointInfo
            {
                get
                {
                    return _featurestextpointInfo;
                }
            }

            /// <summary>
            /// The AtPosTextMath item.
            /// </summary>
            [RepositoryItem("987b9fdc-f2f2-4971-8d12-812a8bebb7a5")]
            public virtual Ranorex.Text AtPosTextMath
            {
                get
                {
                    return _atpostextmathInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AtPosTextMath item info.
            /// </summary>
            [RepositoryItemInfo("987b9fdc-f2f2-4971-8d12-812a8bebb7a5")]
            public virtual RepoItemInfo AtPosTextMathInfo
            {
                get
                {
                    return _atpostextmathInfo;
                }
            }

            /// <summary>
            /// The Angular item.
            /// </summary>
            [RepositoryItem("f5b88d30-368e-45b9-934d-80f28a7da4bf")]
            public virtual Ranorex.RadioButton Angular
            {
                get
                {
                    return _angularInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Angular item info.
            /// </summary>
            [RepositoryItemInfo("f5b88d30-368e-45b9-934d-80f28a7da4bf")]
            public virtual RepoItemInfo AngularInfo
            {
                get
                {
                    return _angularInfo;
                }
            }

            /// <summary>
            /// The Linear item.
            /// </summary>
            [RepositoryItem("188fbd95-2105-4e81-b9d2-675a4efe522b")]
            public virtual Ranorex.RadioButton Linear
            {
                get
                {
                    return _linearInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Linear item info.
            /// </summary>
            [RepositoryItemInfo("188fbd95-2105-4e81-b9d2-675a4efe522b")]
            public virtual RepoItemInfo LinearInfo
            {
                get
                {
                    return _linearInfo;
                }
            }

            /// <summary>
            /// The Expression item.
            /// </summary>
            [RepositoryItem("38ed6664-3127-4f8f-991f-446309e2cde4")]
            public virtual Ranorex.Container Expression
            {
                get
                {
                    return _expressionInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Expression item info.
            /// </summary>
            [RepositoryItemInfo("38ed6664-3127-4f8f-991f-446309e2cde4")]
            public virtual RepoItemInfo ExpressionInfo
            {
                get
                {
                    return _expressionInfo;
                }
            }

            /// <summary>
            /// The Conditions item.
            /// </summary>
            [RepositoryItem("cdf0856d-f429-4a4d-86ab-9bcd1d5c526a")]
            public virtual Ranorex.Container Conditions
            {
                get
                {
                    return _conditionsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Conditions item info.
            /// </summary>
            [RepositoryItemInfo("cdf0856d-f429-4a4d-86ab-9bcd1d5c526a")]
            public virtual RepoItemInfo ConditionsInfo
            {
                get
                {
                    return _conditionsInfo;
                }
            }

            /// <summary>
            /// The GoToStepTextBranch item.
            /// </summary>
            [RepositoryItem("7d2cf70c-9bd5-4b71-81ee-0d15a3175290")]
            public virtual Ranorex.Text GoToStepTextBranch
            {
                get
                {
                    return _gotosteptextbranchInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GoToStepTextBranch item info.
            /// </summary>
            [RepositoryItemInfo("7d2cf70c-9bd5-4b71-81ee-0d15a3175290")]
            public virtual RepoItemInfo GoToStepTextBranchInfo
            {
                get
                {
                    return _gotosteptextbranchInfo;
                }
            }

            /// <summary>
            /// The THENTextBranch item.
            /// </summary>
            [RepositoryItem("be5989c9-9ca1-4acc-a6e2-3738e7e1f96a")]
            public virtual Ranorex.Text THENTextBranch
            {
                get
                {
                    return _thentextbranchInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The THENTextBranch item info.
            /// </summary>
            [RepositoryItemInfo("be5989c9-9ca1-4acc-a6e2-3738e7e1f96a")]
            public virtual RepoItemInfo THENTextBranchInfo
            {
                get
                {
                    return _thentextbranchInfo;
                }
            }

            /// <summary>
            /// The ELSETextBranch item.
            /// </summary>
            [RepositoryItem("82706444-6c12-4b3e-b5fe-11b0520e39f2")]
            public virtual Ranorex.Text ELSETextBranch
            {
                get
                {
                    return _elsetextbranchInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ELSETextBranch item info.
            /// </summary>
            [RepositoryItemInfo("82706444-6c12-4b3e-b5fe-11b0520e39f2")]
            public virtual RepoItemInfo ELSETextBranchInfo
            {
                get
                {
                    return _elsetextbranchInfo;
                }
            }

            /// <summary>
            /// The GoToStepElseBranch item.
            /// </summary>
            [RepositoryItem("9f118903-be1f-4657-88ad-a6c01a4004cc")]
            public virtual Ranorex.Text GoToStepElseBranch
            {
                get
                {
                    return _gotostepelsebranchInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GoToStepElseBranch item info.
            /// </summary>
            [RepositoryItemInfo("9f118903-be1f-4657-88ad-a6c01a4004cc")]
            public virtual RepoItemInfo GoToStepElseBranchInfo
            {
                get
                {
                    return _gotostepelsebranchInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("4d1580fd-cafb-4359-a656-ed636562d100")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _minimumInfo;
            RepoItemInfo _maximumInfo;
            RepoItemInfo _bestfitInfo;
            RepoItemInfo _lineInfo;
            RepoItemInfo _bisectorInfo;
            RepoItemInfo _perpendicularInfo;
            RepoItemInfo _tangentInfo;
            RepoItemInfo _listitem1of2Info;
            RepoItemInfo _listitem2of2Info;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "4d1580fd-cafb-4359-a656-ed636562d100", "")
            {
                _minimumInfo = new RepoItemInfo(this, "Minimum", "listitem[@text='Minimum']", 30000, null, "a1975bc3-6008-4058-bbef-0c1586d70420");
                _maximumInfo = new RepoItemInfo(this, "Maximum", "listitem[@text='Maximum']", 30000, null, "9ed93dc6-9cce-4dc6-a5e7-3c09b434b29b");
                _bestfitInfo = new RepoItemInfo(this, "BestFit", "listitem[@text='BestFit']", 30000, null, "aebd0b9e-940a-4e11-bc82-b6f9955c3deb");
                _lineInfo = new RepoItemInfo(this, "Line", "listitem[@text='Line']", 30000, null, "e0d0c107-1047-4caa-8f2e-4ba7a0716f2e");
                _bisectorInfo = new RepoItemInfo(this, "Bisector", "listitem[@text='Bisector']", 30000, null, "7923f93b-0ee2-4227-bcac-13294b254176");
                _perpendicularInfo = new RepoItemInfo(this, "Perpendicular", "listitem[@text='Perpendicular']", 30000, null, "6e01484b-fe68-4ac4-b02a-99bf902df0c0");
                _tangentInfo = new RepoItemInfo(this, "Tangent", "listitem[@text='Tangent']", 30000, null, "350e9c58-a308-4711-9ad1-b390b5f15f08");
                _listitem1of2Info = new RepoItemInfo(this, "ListItem1Of2", "listitem[@text='1 of 2']", 30000, null, "729b33e6-4263-45c3-bafd-80c45810ea97");
                _listitem2of2Info = new RepoItemInfo(this, "ListItem2Of2", "listitem[@text='2 of 2']", 30000, null, "a9e1f27d-e381-4438-b43d-9fef9c69a2d9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4d1580fd-cafb-4359-a656-ed636562d100")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4d1580fd-cafb-4359-a656-ed636562d100")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Minimum item.
            /// </summary>
            [RepositoryItem("a1975bc3-6008-4058-bbef-0c1586d70420")]
            public virtual Ranorex.ListItem Minimum
            {
                get
                {
                    return _minimumInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Minimum item info.
            /// </summary>
            [RepositoryItemInfo("a1975bc3-6008-4058-bbef-0c1586d70420")]
            public virtual RepoItemInfo MinimumInfo
            {
                get
                {
                    return _minimumInfo;
                }
            }

            /// <summary>
            /// The Maximum item.
            /// </summary>
            [RepositoryItem("9ed93dc6-9cce-4dc6-a5e7-3c09b434b29b")]
            public virtual Ranorex.ListItem Maximum
            {
                get
                {
                    return _maximumInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Maximum item info.
            /// </summary>
            [RepositoryItemInfo("9ed93dc6-9cce-4dc6-a5e7-3c09b434b29b")]
            public virtual RepoItemInfo MaximumInfo
            {
                get
                {
                    return _maximumInfo;
                }
            }

            /// <summary>
            /// The BestFit item.
            /// </summary>
            [RepositoryItem("aebd0b9e-940a-4e11-bc82-b6f9955c3deb")]
            public virtual Ranorex.ListItem BestFit
            {
                get
                {
                    return _bestfitInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The BestFit item info.
            /// </summary>
            [RepositoryItemInfo("aebd0b9e-940a-4e11-bc82-b6f9955c3deb")]
            public virtual RepoItemInfo BestFitInfo
            {
                get
                {
                    return _bestfitInfo;
                }
            }

            /// <summary>
            /// The Line item.
            /// </summary>
            [RepositoryItem("e0d0c107-1047-4caa-8f2e-4ba7a0716f2e")]
            public virtual Ranorex.ListItem Line
            {
                get
                {
                    return _lineInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Line item info.
            /// </summary>
            [RepositoryItemInfo("e0d0c107-1047-4caa-8f2e-4ba7a0716f2e")]
            public virtual RepoItemInfo LineInfo
            {
                get
                {
                    return _lineInfo;
                }
            }

            /// <summary>
            /// The Bisector item.
            /// </summary>
            [RepositoryItem("7923f93b-0ee2-4227-bcac-13294b254176")]
            public virtual Ranorex.ListItem Bisector
            {
                get
                {
                    return _bisectorInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Bisector item info.
            /// </summary>
            [RepositoryItemInfo("7923f93b-0ee2-4227-bcac-13294b254176")]
            public virtual RepoItemInfo BisectorInfo
            {
                get
                {
                    return _bisectorInfo;
                }
            }

            /// <summary>
            /// The Perpendicular item.
            /// </summary>
            [RepositoryItem("6e01484b-fe68-4ac4-b02a-99bf902df0c0")]
            public virtual Ranorex.ListItem Perpendicular
            {
                get
                {
                    return _perpendicularInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Perpendicular item info.
            /// </summary>
            [RepositoryItemInfo("6e01484b-fe68-4ac4-b02a-99bf902df0c0")]
            public virtual RepoItemInfo PerpendicularInfo
            {
                get
                {
                    return _perpendicularInfo;
                }
            }

            /// <summary>
            /// The Tangent item.
            /// </summary>
            [RepositoryItem("350e9c58-a308-4711-9ad1-b390b5f15f08")]
            public virtual Ranorex.ListItem Tangent
            {
                get
                {
                    return _tangentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Tangent item info.
            /// </summary>
            [RepositoryItemInfo("350e9c58-a308-4711-9ad1-b390b5f15f08")]
            public virtual RepoItemInfo TangentInfo
            {
                get
                {
                    return _tangentInfo;
                }
            }

            /// <summary>
            /// The ListItem1Of2 item.
            /// </summary>
            [RepositoryItem("729b33e6-4263-45c3-bafd-80c45810ea97")]
            public virtual Ranorex.ListItem ListItem1Of2
            {
                get
                {
                    return _listitem1of2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem1Of2 item info.
            /// </summary>
            [RepositoryItemInfo("729b33e6-4263-45c3-bafd-80c45810ea97")]
            public virtual RepoItemInfo ListItem1Of2Info
            {
                get
                {
                    return _listitem1of2Info;
                }
            }

            /// <summary>
            /// The ListItem2Of2 item.
            /// </summary>
            [RepositoryItem("a9e1f27d-e381-4438-b43d-9fef9c69a2d9")]
            public virtual Ranorex.ListItem ListItem2Of2
            {
                get
                {
                    return _listitem2of2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem2Of2 item info.
            /// </summary>
            [RepositoryItemInfo("a9e1f27d-e381-4438-b43d-9fef9c69a2d9")]
            public virtual RepoItemInfo ListItem2Of2Info
            {
                get
                {
                    return _listitem2of2Info;
                }
            }
        }

    }
#pragma warning restore 0436
}