///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ConstructButtons
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("74f5002c-7d21-4241-b119-809ad1a42d38", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ConstructButtonsRepository repository.
        /// </summary>
        public static ConstructButtonsRepository repo = ConstructButtonsRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Titlebar' at 808;9.", repo.SnapXUntitled.TitlebarInfo, new RecordItemIndex(1));
            repo.SnapXUntitled.Titlebar.Click("808;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(2));
            Keyboard.Press("{LMenu}");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(3));
            Keyboard.Press("c");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'i'.", new RecordItemIndex(4));
            Keyboard.Press("i");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ConstructStepName' at 173;7.", repo.SnapXUntitled.ConstructStepNameInfo, new RecordItemIndex(5));
            repo.SnapXUntitled.ConstructStepName.Click("173;7");
            Delay.Milliseconds(200);

            string strReadTextOne = repo.SnapXUntitled.ConstructStepName.Caption;
            string strHardcodedText = " Step    1: Intersection";
            StringCompare.Text(strReadTextOne, strHardcodedText);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ModifiersText' at 30;9.", repo.SnapXUntitled.ModifiersTextInfo, new RecordItemIndex(6));
            repo.SnapXUntitled.ModifiersText.Click("30;9");
            Delay.Milliseconds(200);

            string strReadText2 = repo.SnapXUntitled.ModifiersText.TextValue;
            string strHardcodedText2 = "Modifiers";
            StringCompare.Text(strReadText2, strHardcodedText2);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.FeaturesText' at 43;6.", repo.SnapXUntitled.FeaturesTextInfo, new RecordItemIndex(7));
            repo.SnapXUntitled.FeaturesText.Click("43;6");
            Delay.Milliseconds(200);

            string strReadText3 = repo.SnapXUntitled.FeaturesText.TextValue;
            string strHardcodedText3 = "Features:";
            StringCompare.Text(strReadText3, strHardcodedText3);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Value' at 21;5.", repo.SnapXUntitled.ValueInfo, new RecordItemIndex(8));
            repo.SnapXUntitled.Value.Click("21;5");
            Delay.Milliseconds(200);

            string strReadText4 = repo.SnapXUntitled.Value.TextValue;
            string strHardcodedText4 = "0";
            StringCompare.Text(strReadText4, strHardcodedText4);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Features' at 53;12.", repo.SnapXUntitled.FeaturesInfo, new RecordItemIndex(9));
            repo.SnapXUntitled.Features.Click("53;12");
            Delay.Milliseconds(200);

            string strReadText5 = repo.SnapXUntitled.Features.Text;
            string strHardcodedText5 = "Features";
            StringCompare.Text(strReadText5, strHardcodedText5);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonOK' at 37;8.", repo.SnapXUntitled.ButtonOKInfo, new RecordItemIndex(10));
            repo.SnapXUntitled.ButtonOK.Click("37;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.NominalText' at 27;7.", repo.SnapXUntitled.NominalTextInfo, new RecordItemIndex(11));
            repo.SnapXUntitled.NominalText.Click("27;7");
            Delay.Milliseconds(200);

            string strReadText6 = repo.SnapXUntitled.NominalText.TextValue;
            string strHardcodedText6 = "Nominal";
            StringCompare.Text(strReadText6, strHardcodedText6);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.UpperText' at 29;9.", repo.SnapXUntitled.UpperTextInfo, new RecordItemIndex(12));
            repo.SnapXUntitled.UpperText.Click("29;9");
            Delay.Milliseconds(200);

            string strReadText7 = repo.SnapXUntitled.UpperText.TextValue;
            string strHardcodedText7 = "Upper";
            StringCompare.Text(strReadText7, strHardcodedText7);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.LowerText' at 27;7.", repo.SnapXUntitled.LowerTextInfo, new RecordItemIndex(13));
            repo.SnapXUntitled.LowerText.Click("27;7");
            Delay.Milliseconds(200);

            string strReadText8 = repo.SnapXUntitled.LowerText.TextValue;
            string strHardcodedText8 = "Lower";
            StringCompare.Text(strReadText8, strHardcodedText8);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.GeometricToleranceText' at 47;7.", repo.SnapXUntitled.GeometricToleranceTextInfo, new RecordItemIndex(14));
            repo.SnapXUntitled.GeometricToleranceText.Click("47;7");
            Delay.Milliseconds(200);

            string strReadText9 = repo.SnapXUntitled.GeometricToleranceText.TextValue;
            string strHardcodedText9 = "Geometric Tolerances";
            StringCompare.Text(strReadText9, strHardcodedText9);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ANSI' at 39;7.", repo.SnapXUntitled.ANSIInfo, new RecordItemIndex(15));
            repo.SnapXUntitled.ANSI.Click("39;7");
            Delay.Milliseconds(200);

            string strReadText10 = repo.SnapXUntitled.ANSI.Text;
            string strHardcodedText10 = "ANSI";
            StringCompare.Text(strReadText10, strHardcodedText10);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RadioButtonISO' at 32;7.", repo.SnapXUntitled.RadioButtonISOInfo, new RecordItemIndex(16));
            repo.SnapXUntitled.RadioButtonISO.Click("32;7");
            Delay.Milliseconds(200);

            string strReadText11 = repo.SnapXUntitled.RadioButtonISO.Text;
            string strHardcodedText11 = "ISO";
            StringCompare.Text(strReadText11, strHardcodedText11);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.PositionText' at 47;13.", repo.SnapXUntitled.PositionTextInfo, new RecordItemIndex(17));
            repo.SnapXUntitled.PositionText.Click("47;13");
            Delay.Milliseconds(200);

            string strReadText12 = repo.SnapXUntitled.PositionText.TextValue;
            string strHardcodedText12 = "Position";
            StringCompare.Text(strReadText12, strHardcodedText12);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DataStream' at 49;7.", repo.SnapXUntitled.DataStreamInfo, new RecordItemIndex(18));
            repo.SnapXUntitled.DataStream.Click("49;7");
            Delay.Milliseconds(200);

            string strReadText13 = repo.SnapXUntitled.DataStream.Text;
            string strHardcodedText13 = "Data Stream";
            StringCompare.Text(strReadText13, strHardcodedText13);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Skip' at 46;9.", repo.SnapXUntitled.SkipInfo, new RecordItemIndex(19));
            repo.SnapXUntitled.Skip.Click("46;9");
            Delay.Milliseconds(200);

            string strReadText14 = repo.SnapXUntitled.Skip.Text;
            string strHardcodedText14 = "Skip";
            StringCompare.Text(strReadText14, strHardcodedText14);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Hide' at 42;9.", repo.SnapXUntitled.HideInfo, new RecordItemIndex(20));
            repo.SnapXUntitled.Hide.Click("42;9");
            Delay.Milliseconds(200);

            string strReadText15 = repo.SnapXUntitled.Hide.Text;
            string strHardcodedText15 = "Hide";
            StringCompare.Text(strReadText15, strHardcodedText15);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(21));
            Keyboard.Press("c");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Titlebar' at 808;9.", repo.SnapXUntitled.TitlebarInfo, new RecordItemIndex(22));
            repo.SnapXUntitled.Titlebar.Click("808;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(23));
            Keyboard.Press("{LMenu}");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(24));
            Keyboard.Press("c");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'w'.", new RecordItemIndex(25));
            Keyboard.Press("w");
            Delay.Milliseconds(0);

            /////////////////////////// Continue from Here ////////////////////////////////////

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ConstructStepName' at 118;7.", repo.SnapXUntitled.ConstructStepNameInfo, new RecordItemIndex(26));
            repo.SnapXUntitled.ConstructStepName.Click("118;7");
            Delay.Milliseconds(200);

            string strReadText16 = repo.SnapXUntitled.ConstructStepName.TextValue;
            string strHardcodedText16 = " Step    1: Width";
            StringCompare.Text(strReadText16, strHardcodedText16);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ModifiersText' at 44;9.", repo.SnapXUntitled.ModifiersTextInfo, new RecordItemIndex(27));
            repo.SnapXUntitled.ModifiersText.Click("44;9");
            Delay.Milliseconds(200);

            string strReadText17 = repo.SnapXUntitled.ModifiersText.TextValue;
            string strHardcodedText17 = "Modifiers";
            StringCompare.Text(strReadText17, strHardcodedText17);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FeaturesTextWidth' at 35;5.", repo.SnapXUntitled.FeaturesTextWidthInfo, new RecordItemIndex(28));
            repo.SnapXUntitled.FeaturesTextWidth.Click("35;5");
            Delay.Milliseconds(200);

            string strReadText18 = repo.SnapXUntitled.FeaturesTextWidth.TextValue;
            string strHardcodedText18 = "Features:";
            StringCompare.Text(strReadText18, strHardcodedText18);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ValueWidth' at 18;5.", repo.SnapXUntitled.ValueWidthInfo, new RecordItemIndex(29));
            repo.SnapXUntitled.ValueWidth.Click("18;5");
            Delay.Milliseconds(200);

            string strReadText19 = repo.SnapXUntitled.ValueWidth.TextValue;
            string strHardcodedText19 = "0";
            StringCompare.Text(strReadText19, strHardcodedText19);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FeaturesWidth' at 41;10.", repo.SnapXUntitled.FeaturesWidthInfo, new RecordItemIndex(30));
            repo.SnapXUntitled.FeaturesWidth.Click("41;10");
            Delay.Milliseconds(200);

            string strReadText20 = repo.SnapXUntitled.FeaturesWidth.Text;
            string strHardcodedText20 = "Features";
            StringCompare.Text(strReadText20, strHardcodedText20);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonOK' at 34;11.", repo.SnapXUntitled.ButtonOKInfo, new RecordItemIndex(31));
            repo.SnapXUntitled.ButtonOK.Click("34;11");
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.NominalText' at 21;7.", repo.SnapXUntitled.NominalTextInfo, new RecordItemIndex(32));
            repo.SnapXUntitled.NominalText.Click("21;7");
            Delay.Milliseconds(200);

            string strReadText21 = repo.SnapXUntitled.NominalText.TextValue;
            string strHardcodedText21 = "Nominal";
            StringCompare.Text(strReadText21, strHardcodedText21);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.UpperText' at 23;9.", repo.SnapXUntitled.UpperTextInfo, new RecordItemIndex(33));
            repo.SnapXUntitled.UpperText.Click("23;9");
            Delay.Milliseconds(200);

            string strReadText22 = repo.SnapXUntitled.UpperText.TextValue;
            string strHardcodedText22 = "Upper";
            StringCompare.Text(strReadText22, strHardcodedText22);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.LowerText' at 29;7.", repo.SnapXUntitled.LowerTextInfo, new RecordItemIndex(34));
            repo.SnapXUntitled.LowerText.Click("29;7");
            Delay.Milliseconds(200);

            string strReadText23 = repo.SnapXUntitled.LowerText.TextValue;
            string strHardcodedText23 = "Lower";
            StringCompare.Text(strReadText23, strHardcodedText23);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.GeometricToleranceText' at 85;7.", repo.SnapXUntitled.GeometricToleranceTextInfo, new RecordItemIndex(35));
            repo.SnapXUntitled.GeometricToleranceText.Click("85;7");
            Delay.Milliseconds(200);

            string strReadText24 = repo.SnapXUntitled.GeometricToleranceText.TextValue;
            string strHardcodedText24 = "Geometric Tolerances";
            StringCompare.Text(strReadText24, strHardcodedText24);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ANSI' at 37;8.", repo.SnapXUntitled.ANSIInfo, new RecordItemIndex(36));
            repo.SnapXUntitled.ANSI.Click("37;8");
            Delay.Milliseconds(200);

            string strReadText25 = repo.SnapXUntitled.ANSI.Text;
            string strHardcodedText25 = "ANSI";
            StringCompare.Text(strReadText25, strHardcodedText25);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RadioButtonISO' at 25;5.", repo.SnapXUntitled.RadioButtonISOInfo, new RecordItemIndex(37));
            repo.SnapXUntitled.RadioButtonISO.Click("25;5");
            Delay.Milliseconds(200);

            string strReadText26 = repo.SnapXUntitled.RadioButtonISO.Text;
            string strHardcodedText26 = "ISO";
            StringCompare.Text(strReadText26, strHardcodedText26);
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.PositionText' at 39;10.", repo.SnapXUntitled.PositionTextInfo, new RecordItemIndex(38));
            repo.SnapXUntitled.PositionText.Click("39;10");
            Delay.Milliseconds(200);

            string strReadText27 = repo.SnapXUntitled.PositionText.TextValue;
            string strHardcodedText27 = "Position";
            StringCompare.Text(strReadText27, strHardcodedText27);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonID' at 24;8.", repo.SnapXUntitled.RadioButtonIDInfo, new RecordItemIndex(39));
            repo.SnapXUntitled.RadioButtonID.Click("24;8");
            Delay.Milliseconds(200);

            string strReadText28 = repo.SnapXUntitled.RadioButtonID.Text;
            string strHardcodedText28 = "ID";
            StringCompare.Text(strReadText28, strHardcodedText28);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonOD' at 31;7.", repo.SnapXUntitled.RadioButtonODInfo, new RecordItemIndex(40));
            repo.SnapXUntitled.RadioButtonOD.Click("31;7");
            Delay.Milliseconds(200);

            string strReadText29 = repo.SnapXUntitled.RadioButtonOD.Text;
            string strHardcodedText29 = "OD";
            StringCompare.Text(strReadText29, strHardcodedText29);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonRFS' at 31;8.", repo.SnapXUntitled.RadioButtonRFSInfo, new RecordItemIndex(41));
            repo.SnapXUntitled.RadioButtonRFS.Click("31;8");
            Delay.Milliseconds(200);

            string strReadText30 = repo.SnapXUntitled.RadioButtonRFS.Text;
            string strHardcodedText30 = "RFS";
            StringCompare.Text(strReadText30, strHardcodedText30);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonMMC' at 29;7.", repo.SnapXUntitled.RadioButtonMMCInfo, new RecordItemIndex(42));
            repo.SnapXUntitled.RadioButtonMMC.Click("29;7");
            Delay.Milliseconds(200);

            string strReadText31 = repo.SnapXUntitled.RadioButtonMMC.Text;
            string strHardcodedText31 = "MMC";
            StringCompare.Text(strReadText31, strHardcodedText31);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonLMC' at 31;6.", repo.SnapXUntitled.RadioButtonLMCInfo, new RecordItemIndex(43));
            repo.SnapXUntitled.RadioButtonLMC.Click("31;6");
            Delay.Milliseconds(200);

            string strReadText32 = repo.SnapXUntitled.RadioButtonLMC.Text;
            string strHardcodedText32 = "LMC";
            StringCompare.Text(strReadText32, strHardcodedText32);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DiametricalToleranceZone' at 83;9.", repo.SnapXUntitled.DiametricalToleranceZoneInfo, new RecordItemIndex(44));
            repo.SnapXUntitled.DiametricalToleranceZone.Click("83;9");
            Delay.Milliseconds(200);

            string strReadText33 = repo.SnapXUntitled.DiametricalToleranceZone.Text;
            string strHardcodedText33 = "Diametrical tolerance zone";
            StringCompare.Text(strReadText33, strHardcodedText33);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DataStream' at 54;7.", repo.SnapXUntitled.DataStreamInfo, new RecordItemIndex(45));
            repo.SnapXUntitled.DataStream.Click("54;7");
            Delay.Milliseconds(200);

            string strReadText34 = repo.SnapXUntitled.DataStream.Text;
            string strHardcodedText34 = "Data Stream";
            StringCompare.Text(strReadText34, strHardcodedText34);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Skip' at 33;10.", repo.SnapXUntitled.SkipInfo, new RecordItemIndex(46));
            repo.SnapXUntitled.Skip.Click("33;10");
            Delay.Milliseconds(200);

            string strReadText35 = repo.SnapXUntitled.Skip.Text;
            string strHardcodedText35 = "Skip";
            StringCompare.Text(strReadText35, strHardcodedText35);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Hide' at 38;9.", repo.SnapXUntitled.HideInfo, new RecordItemIndex(47));
            repo.SnapXUntitled.Hide.Click("38;9");
            Delay.Milliseconds(200);

            string strReadText36 = repo.SnapXUntitled.Hide.Text;
            string strHardcodedText36 = "Hide";
            StringCompare.Text(strReadText36, strHardcodedText36);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButton' at 6;10.", repo.SnapXUntitled.DropDownButtonInfo, new RecordItemIndex(48));
            repo.SnapXUntitled.DropDownButton.Click("6;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.BestFit' at Center.", repo.List1000.BestFitInfo, new RecordItemIndex(48));
            repo.List1000.BestFit.Click();
            Delay.Milliseconds(200);

            string strReadText37 = repo.List1000.BestFit.Text;
            string strHardcodedText37 = "BestFit";
            StringCompare.Text(strReadText37, strHardcodedText37);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButton' at Center.", repo.SnapXUntitled.DropDownButtonInfo, new RecordItemIndex(50));
            repo.SnapXUntitled.DropDownButton.Click();
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Minimum' at 81;6.", repo.List1000.MinimumInfo, new RecordItemIndex(49));
            repo.List1000.Minimum.Click("81;6");
            Delay.Milliseconds(200);

            string strReadText38 = repo.List1000.Minimum.Text;
            string strHardcodedText38 = "Minimum";
            StringCompare.Text(strReadText38, strHardcodedText38);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButton' at Center.", repo.SnapXUntitled.DropDownButtonInfo, new RecordItemIndex(50));
            repo.SnapXUntitled.DropDownButton.Click();
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Maximum' at 87;6.", repo.List1000.MaximumInfo, new RecordItemIndex(51));
            repo.List1000.Maximum.Click("87;6");
            Delay.Milliseconds(200);

            string strReadText39 = repo.List1000.Maximum.Text;
            string strHardcodedText39 = "Maximum";
            StringCompare.Text(strReadText39, strHardcodedText39);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonCancel' at 67;10.", repo.SnapXUntitled.ButtonCancelInfo, new RecordItemIndex(52));
            repo.SnapXUntitled.ButtonCancel.Click("67;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Titlebar' at Center.", repo.SnapXUntitled.TitlebarInfo, new RecordItemIndex(53));
            repo.SnapXUntitled.Titlebar.Click();
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(54));
            Keyboard.Press("{LMenu}");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(55));
            Keyboard.Press("c");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(56));
            Keyboard.Press("c");
            Delay.Milliseconds(0);

            //////////////////// Continue from here /////////////////////////////////////////

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ConstructStepName' at 142;8.", repo.SnapXUntitled.ConstructStepNameInfo, new RecordItemIndex(57));
            repo.SnapXUntitled.ConstructStepName.Click("142;8");
            Delay.Milliseconds(200);

            string strReadText40 = repo.SnapXUntitled.ConstructStepName.TextValue;
            string strHardcodedText40 = "Step 1: Circle";
            StringCompare.Text(strReadText40, strHardcodedText40);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ModifiersText' at 24;5.", repo.SnapXUntitled.ModifiersTextInfo, new RecordItemIndex(58));
            repo.SnapXUntitled.ModifiersText.Click("24;5");
            Delay.Milliseconds(200);

            string strReadText41 = repo.SnapXUntitled.ModifiersText.TextValue;
            string strHardcodedText41 = "Modifiers";
            StringCompare.Text(strReadText41, strHardcodedText41);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.CompositeText' at 57;7.", repo.SnapXUntitled.CompositeTextInfo, new RecordItemIndex(59));
            repo.SnapXUntitled.CompositeText.Click("57;7");
            Delay.Milliseconds(200);

            string strReadText42 = repo.SnapXUntitled.CompositeText.Text;
            string strHardcodedText42 = "Composite";
            StringCompare.Text(strReadText42, strHardcodedText42);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.FeaturesTextCircle' at 24;4.", repo.SnapXUntitled.FeaturesTextCircleInfo, new RecordItemIndex(60));
            repo.SnapXUntitled.FeaturesTextCircle.Click("24;4");
            Delay.Milliseconds(200);

            string strReadText43 = repo.SnapXUntitled.FeaturesTextCircle.TextValue;
            string strHardcodedText43 = "Features:";
            StringCompare.Text(strReadText43, strHardcodedText43);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ValueCircle' at 20;5.", repo.SnapXUntitled.ValueCircleInfo, new RecordItemIndex(61));
            repo.SnapXUntitled.ValueCircle.Click("20;5");
            Delay.Milliseconds(200);

            string strReadText44 = repo.SnapXUntitled.ValueCircle.TextValue;
            string strHardcodedText44 = "0";
            StringCompare.Text(strReadText44, strHardcodedText44);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Features1' at 38;8.", repo.SnapXUntitled.Features1Info, new RecordItemIndex(62));
            repo.SnapXUntitled.Features1.Click("38;8");
            Delay.Milliseconds(200);

            string strReadText45 = repo.SnapXUntitled.Features1.Text;
            string strHardcodedText45 = "Features";
            StringCompare.Text(strReadText45, strHardcodedText45);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonOK' at 24;9.", repo.SnapXUntitled.ButtonOKInfo, new RecordItemIndex(63));
            repo.SnapXUntitled.ButtonOK.Click("24;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RadiusCircle' at 44;8.", repo.SnapXUntitled.RadiusCircleInfo, new RecordItemIndex(64));
            repo.SnapXUntitled.RadiusCircle.Click("44;8");
            Delay.Milliseconds(200);

            string strReadText46 = repo.SnapXUntitled.RadiusCircle.Text;
            string strHardcodedText46 = "Radius";
            StringCompare.Text(strReadText46, strHardcodedText46);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DiameterCircle' at 44;10.", repo.SnapXUntitled.DiameterCircleInfo, new RecordItemIndex(65));
            repo.SnapXUntitled.DiameterCircle.Click("44;10");
            Delay.Milliseconds(200);

            string strReadText47 = repo.SnapXUntitled.DiameterCircle.Text;
            string strHardcodedText47 = "Diameter";
            StringCompare.Text(strReadText47, strHardcodedText47);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.NominalText' at 13;7.", repo.SnapXUntitled.NominalTextInfo, new RecordItemIndex(66));
            repo.SnapXUntitled.NominalText.Click("13;7");
            Delay.Milliseconds(200);

            string strReadText48 = repo.SnapXUntitled.NominalText.TextValue;
            string strHardcodedText48 = "Nominal";
            StringCompare.Text(strReadText48, strHardcodedText48);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SnapXUntitled.UpperText' at 26;8.", repo.SnapXUntitled.UpperTextInfo, new RecordItemIndex(67));
            repo.SnapXUntitled.UpperText.Click("26;8");
            Delay.Milliseconds(200);

            string strReadText49 = repo.SnapXUntitled.UpperText.TextValue;
            string strHardcodedText49 = "Upper";
            StringCompare.Text(strReadText49, strHardcodedText49);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.LowerText' at 21;6.", repo.SnapXUntitled.LowerTextInfo, new RecordItemIndex(68));
            repo.SnapXUntitled.LowerText.Click("21;6");
            Delay.Milliseconds(200);

            string strReadText50 = repo.SnapXUntitled.LowerText.TextValue;
            string strHardcodedText50 = "Lower";
            StringCompare.Text(strReadText50, strHardcodedText50);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.GeometricToleranceText' at 114;6.", repo.SnapXUntitled.GeometricToleranceTextInfo, new RecordItemIndex(69));
            repo.SnapXUntitled.GeometricToleranceText.Click("114;6");
            Delay.Milliseconds(200);

            string strReadText51 = repo.SnapXUntitled.GeometricToleranceText.TextValue;
            string strHardcodedText51 = "Geometric Tolerances";
            StringCompare.Text(strReadText51, strHardcodedText51);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ANSI' at 28;6.", repo.SnapXUntitled.ANSIInfo, new RecordItemIndex(70));
            repo.SnapXUntitled.ANSI.Click("28;6");
            Delay.Milliseconds(200);

            string strReadText52 = repo.SnapXUntitled.ANSI.Text;
            string strHardcodedText52 = "ANSI";
            StringCompare.Text(strReadText52, strHardcodedText52);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RadioButtonISO' at 26;6.", repo.SnapXUntitled.RadioButtonISOInfo, new RecordItemIndex(71));
            repo.SnapXUntitled.RadioButtonISO.Click("26;6");
            Delay.Milliseconds(200);

            string strReadText53 = repo.SnapXUntitled.RadioButtonISO.Text;
            string strHardcodedText53 = "ISO";
            StringCompare.Text(strReadText53, strHardcodedText53);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.CircularityText' at 46;12.", repo.SnapXUntitled.CircularityTextInfo, new RecordItemIndex(72));
            repo.SnapXUntitled.CircularityText.Click("46;12");
            Delay.Milliseconds(200);

            string strReadText54 = repo.SnapXUntitled.CircularityText.TextValue;
            string strHardcodedText54 = "Circularity";
            StringCompare.Text(strReadText54, strHardcodedText54);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.PositionText' at 48;12.", repo.SnapXUntitled.PositionTextInfo, new RecordItemIndex(73));
            repo.SnapXUntitled.PositionText.Click("48;12");
            Delay.Milliseconds(200);

            string strReadText55 = repo.SnapXUntitled.PositionText.TextValue;
            string strHardcodedText55 = "Position";
            StringCompare.Text(strReadText55, strHardcodedText55);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ConcentricityText' at 44;11.", repo.SnapXUntitled.ConcentricityTextInfo, new RecordItemIndex(74));
            repo.SnapXUntitled.ConcentricityText.Click("44;11");
            Delay.Milliseconds(200);

            string strReadText56 = repo.SnapXUntitled.ConcentricityText.TextValue;
            string strHardcodedText56 = "Concentricity";
            StringCompare.Text(strReadText56, strHardcodedText56);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ProfileText' at 40;12.", repo.SnapXUntitled.ProfileTextInfo, new RecordItemIndex(75));
            repo.SnapXUntitled.ProfileText.Click("40;12");
            Delay.Milliseconds(200);

            string strReadText57 = repo.SnapXUntitled.ProfileText.TextValue;
            string strHardcodedText57 = "Profile";
            StringCompare.Text(strReadText57, strHardcodedText57);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonID' at 23;6.", repo.SnapXUntitled.RadioButtonIDInfo, new RecordItemIndex(76));
            repo.SnapXUntitled.RadioButtonID.Click("23;6");
            Delay.Milliseconds(200);

            string strReadText58 = repo.SnapXUntitled.RadioButtonID.Text;
            string strHardcodedText58 = "ID";
            StringCompare.Text(strReadText58, strHardcodedText58);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonOD' at 28;7.", repo.SnapXUntitled.RadioButtonODInfo, new RecordItemIndex(77));
            repo.SnapXUntitled.RadioButtonOD.Click("28;7");
            Delay.Milliseconds(200);

            string strReadText59 = repo.SnapXUntitled.RadioButtonOD.Text;
            string strHardcodedText59 = "OD";
            StringCompare.Text(strReadText59, strHardcodedText59);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonRFS' at 25;8.", repo.SnapXUntitled.RadioButtonRFSInfo, new RecordItemIndex(78));
            repo.SnapXUntitled.RadioButtonRFS.Click("25;8");
            Delay.Milliseconds(200);

            string strReadText60 = repo.SnapXUntitled.RadioButtonRFS.Text;
            string strHardcodedText60 = "RFS";
            StringCompare.Text(strReadText60, strHardcodedText60);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonMMC' at 37;8.", repo.SnapXUntitled.RadioButtonMMCInfo, new RecordItemIndex(79));
            repo.SnapXUntitled.RadioButtonMMC.Click("37;8");
            Delay.Milliseconds(200);

            string strReadText61 = repo.SnapXUntitled.RadioButtonMMC.Text;
            string strHardcodedText61 = "MMC";
            StringCompare.Text(strReadText61, strHardcodedText61);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RadioButtonLMC' at 29;8.", repo.SnapXUntitled.RadioButtonLMCInfo, new RecordItemIndex(80));
            repo.SnapXUntitled.RadioButtonLMC.Click("29;8");
            Delay.Milliseconds(200);

            string strReadText62 = repo.SnapXUntitled.RadioButtonLMC.Text;
            string strHardcodedText62 = "LMC";
            StringCompare.Text(strReadText62, strHardcodedText62);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RefTextOne' at 15;7.", repo.SnapXUntitled.RefTextOneInfo, new RecordItemIndex(81));
            repo.SnapXUntitled.RefTextOne.Click("15;7");
            Delay.Milliseconds(200);

            string strReadText63 = repo.SnapXUntitled.RefTextOne.TextValue;
            string strHardcodedText63 = "Ref #";
            StringCompare.Text(strReadText63, strHardcodedText63);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DataStream' at 43;11.", repo.SnapXUntitled.DataStreamInfo, new RecordItemIndex(82));
            repo.SnapXUntitled.DataStream.Click("43;11");
            Delay.Milliseconds(200);

            string strReadText64 = repo.SnapXUntitled.DataStream.Text;
            string strHardcodedText64 = "Data Stream";
            StringCompare.Text(strReadText64, strHardcodedText64);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Skip' at 30;9.", repo.SnapXUntitled.SkipInfo, new RecordItemIndex(83));
            repo.SnapXUntitled.Skip.Click("30;9");
            Delay.Milliseconds(200);

            string strReadText65 = repo.SnapXUntitled.Skip.Text;
            string strHardcodedText65 = "Skip";
            StringCompare.Text(strReadText65, strHardcodedText65);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Hide' at 31;10.", repo.SnapXUntitled.HideInfo, new RecordItemIndex(84));
            repo.SnapXUntitled.Hide.Click("31;10");
            Delay.Milliseconds(200);

            string strReadText66 = repo.SnapXUntitled.Hide.Text;
            string strHardcodedText66 = "Hide";
            StringCompare.Text(strReadText66, strHardcodedText66);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButton' at 7;9.", repo.SnapXUntitled.DropDownButtonInfo, new RecordItemIndex(85));
            repo.SnapXUntitled.DropDownButton.Click("7;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.BestFit' at 86;5.", repo.List1000.BestFitInfo, new RecordItemIndex(86));
            repo.List1000.BestFit.Click("86;5");
            Delay.Milliseconds(200);

            string strReadText67 = repo.List1000.BestFit.Text;
            string strHardcodedText67 = "BetFit";
            StringCompare.Text(strReadText67, strHardcodedText67);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButton' at 8;10.", repo.SnapXUntitled.DropDownButtonInfo, new RecordItemIndex(87));
            repo.SnapXUntitled.DropDownButton.Click("8;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Minimum' at 82;4.", repo.List1000.MinimumInfo, new RecordItemIndex(88));
            repo.List1000.Minimum.Click("82;4");
            Delay.Milliseconds(200);

            string strReadText68 = repo.List1000.Minimum.Text;
            string strHardcodedText68 = "Minimum";
            StringCompare.Text(strReadText68, strHardcodedText68);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButton' at 8;11.", repo.SnapXUntitled.DropDownButtonInfo, new RecordItemIndex(89));
            repo.SnapXUntitled.DropDownButton.Click("8;11");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Maximum' at 79;6.", repo.List1000.MaximumInfo, new RecordItemIndex(90));
            repo.List1000.Maximum.Click("79;6");
            Delay.Milliseconds(200);

            string strReadText69 = repo.List1000.Maximum.Text;
            string strHardcodedText69 = "Maximum";
            StringCompare.Text(strReadText69, strHardcodedText69);
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonCancel' at 68;14.", repo.SnapXUntitled.ButtonCancelInfo, new RecordItemIndex(91));
            repo.SnapXUntitled.ButtonCancel.Click("68;14");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Titlebar' at Center.", repo.SnapXUntitled.TitlebarInfo, new RecordItemIndex(92));
            repo.SnapXUntitled.Titlebar.Click();
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(93));
            Keyboard.Press("{LMenu}");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(94));
            Keyboard.Press("c");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'l'.", new RecordItemIndex(95));
            Keyboard.Press("l");
            Delay.Milliseconds(0);

            //////////////////// Continue From here /////////////////////

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ModifiersText' at 46;7.", repo.SnapXUntitled.ModifiersTextInfo, new RecordItemIndex(96));
            repo.SnapXUntitled.ModifiersText.Click("46;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.CompositeText' at 56;12.", repo.SnapXUntitled.CompositeTextInfo, new RecordItemIndex(97));
            repo.SnapXUntitled.CompositeText.Click("56;12");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.FeaturesTextLine' at 25;5.", repo.SnapXUntitled.FeaturesTextLineInfo, new RecordItemIndex(98));
            repo.SnapXUntitled.FeaturesTextLine.Click("25;5");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ValueLine' at 14;5.", repo.SnapXUntitled.ValueLineInfo, new RecordItemIndex(99));
            repo.SnapXUntitled.ValueLine.Click("14;5");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Features2' at 39;8.", repo.SnapXUntitled.Features2Info, new RecordItemIndex(100));
            repo.SnapXUntitled.Features2.Click("39;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonOK' at 40;9.", repo.SnapXUntitled.ButtonOKInfo, new RecordItemIndex(101));
            repo.SnapXUntitled.ButtonOK.Click("40;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButtonLineOne' at 8;8.", repo.SnapXUntitled.DropDownButtonLineOneInfo, new RecordItemIndex(102));
            repo.SnapXUntitled.DropDownButtonLineOne.Click("8;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Line' at 86;6.", repo.List1000.LineInfo, new RecordItemIndex(103));
            repo.List1000.Line.Click("86;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButtonLineOne' at 8;10.", repo.SnapXUntitled.DropDownButtonLineOneInfo, new RecordItemIndex(104));
            repo.SnapXUntitled.DropDownButtonLineOne.Click("8;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Bisector' at 82;8.", repo.List1000.BisectorInfo, new RecordItemIndex(105));
            repo.List1000.Bisector.Click("82;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButtonLineOne' at 7;13.", repo.SnapXUntitled.DropDownButtonLineOneInfo, new RecordItemIndex(106));
            repo.SnapXUntitled.DropDownButtonLineOne.Click("7;13");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Perpendicular' at 83;8.", repo.List1000.PerpendicularInfo, new RecordItemIndex(107));
            repo.List1000.Perpendicular.Click("83;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButtonLineOne' at 9;10.", repo.SnapXUntitled.DropDownButtonLineOneInfo, new RecordItemIndex(108));
            repo.SnapXUntitled.DropDownButtonLineOne.Click("9;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Tangent' at 82;8.", repo.List1000.TangentInfo, new RecordItemIndex(109));
            repo.List1000.Tangent.Click("82;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButtonLineTwo' at 7;11.", repo.SnapXUntitled.DropDownButtonLineTwoInfo, new RecordItemIndex(110));
            repo.SnapXUntitled.DropDownButtonLineTwo.Click("7;11");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItem1Of2' at 90;7.", repo.List1000.ListItem1Of2Info, new RecordItemIndex(111));
            repo.List1000.ListItem1Of2.Click("90;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButtonLineTwo' at 11;8.", repo.SnapXUntitled.DropDownButtonLineTwoInfo, new RecordItemIndex(112));
            repo.SnapXUntitled.DropDownButtonLineTwo.Click("11;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItem2Of2' at 94;6.", repo.List1000.ListItem2Of2Info, new RecordItemIndex(113));
            repo.List1000.ListItem2Of2.Click("94;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButton' at 9;11.", repo.SnapXUntitled.DropDownButtonInfo, new RecordItemIndex(114));
            repo.SnapXUntitled.DropDownButton.Click("9;11");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.BestFit' at 83;7.", repo.List1000.BestFitInfo, new RecordItemIndex(115));
            repo.List1000.BestFit.Click("83;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButton' at 9;8.", repo.SnapXUntitled.DropDownButtonInfo, new RecordItemIndex(116));
            repo.SnapXUntitled.DropDownButton.Click("9;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Minimum' at 84;4.", repo.List1000.MinimumInfo, new RecordItemIndex(117));
            repo.List1000.Minimum.Click("84;4");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DropDownButton' at 8;10.", repo.SnapXUntitled.DropDownButtonInfo, new RecordItemIndex(118));
            repo.SnapXUntitled.DropDownButton.Click("8;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Maximum' at 80;6.", repo.List1000.MaximumInfo, new RecordItemIndex(119));
            repo.List1000.Maximum.Click("80;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.NominalText' at 34;7.", repo.SnapXUntitled.NominalTextInfo, new RecordItemIndex(120));
            repo.SnapXUntitled.NominalText.Click("34;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.UpperText' at 23;8.", repo.SnapXUntitled.UpperTextInfo, new RecordItemIndex(121));
            repo.SnapXUntitled.UpperText.Click("23;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.LowerText' at 21;7.", repo.SnapXUntitled.LowerTextInfo, new RecordItemIndex(122));
            repo.SnapXUntitled.LowerText.Click("21;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.GeometricToleranceText' at 96;6.", repo.SnapXUntitled.GeometricToleranceTextInfo, new RecordItemIndex(123));
            repo.SnapXUntitled.GeometricToleranceText.Click("96;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ANSI' at 34;6.", repo.SnapXUntitled.ANSIInfo, new RecordItemIndex(124));
            repo.SnapXUntitled.ANSI.Click("34;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RadioButtonISO' at 30;3.", repo.SnapXUntitled.RadioButtonISOInfo, new RecordItemIndex(125));
            repo.SnapXUntitled.RadioButtonISO.Click("30;3");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.StraightnessText' at 54;9.", repo.SnapXUntitled.StraightnessTextInfo, new RecordItemIndex(126));
            repo.SnapXUntitled.StraightnessText.Click("54;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ProfileText' at 48;11.", repo.SnapXUntitled.ProfileTextInfo, new RecordItemIndex(127));
            repo.SnapXUntitled.ProfileText.Click("48;11");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ParallelismText' at 48;11.", repo.SnapXUntitled.ParallelismTextInfo, new RecordItemIndex(128));
            repo.SnapXUntitled.ParallelismText.Click("48;11");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.PerpendicularityText' at 48;11.", repo.SnapXUntitled.PerpendicularityTextInfo, new RecordItemIndex(129));
            repo.SnapXUntitled.PerpendicularityText.Click("48;11");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.AngularityText' at 46;14.", repo.SnapXUntitled.AngularityTextInfo, new RecordItemIndex(130));
            repo.SnapXUntitled.AngularityText.Click("46;14");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RefTextOne' at 13;8.", repo.SnapXUntitled.RefTextOneInfo, new RecordItemIndex(131));
            repo.SnapXUntitled.RefTextOne.Click("13;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RefTextTwo' at 12;6.", repo.SnapXUntitled.RefTextTwoInfo, new RecordItemIndex(132));
            repo.SnapXUntitled.RefTextTwo.Click("12;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RefTextThree' at 13;10.", repo.SnapXUntitled.RefTextThreeInfo, new RecordItemIndex(133));
            repo.SnapXUntitled.RefTextThree.Click("13;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.AngleText' at 15;9.", repo.SnapXUntitled.AngleTextInfo, new RecordItemIndex(134));
            repo.SnapXUntitled.AngleText.Click("15;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DataStream' at 69;12.", repo.SnapXUntitled.DataStreamInfo, new RecordItemIndex(135));
            repo.SnapXUntitled.DataStream.Click("69;12");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Skip' at 30;9.", repo.SnapXUntitled.SkipInfo, new RecordItemIndex(136));
            repo.SnapXUntitled.Skip.Click("30;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Hide' at 40;8.", repo.SnapXUntitled.HideInfo, new RecordItemIndex(137));
            repo.SnapXUntitled.Hide.Click("40;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonCancel' at 53;10.", repo.SnapXUntitled.ButtonCancelInfo, new RecordItemIndex(138));
            repo.SnapXUntitled.ButtonCancel.Click("53;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Titlebar' at Center.", repo.SnapXUntitled.TitlebarInfo, new RecordItemIndex(139));
            repo.SnapXUntitled.Titlebar.Click();
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(140));
            Keyboard.Press("{LMenu}");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(141));
            Keyboard.Press("c");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'p'.", new RecordItemIndex(142));
            Keyboard.Press("p");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ConstructStepName' at 126;10.", repo.SnapXUntitled.ConstructStepNameInfo, new RecordItemIndex(143));
            repo.SnapXUntitled.ConstructStepName.Click("126;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ModifiersText' at 42;6.", repo.SnapXUntitled.ModifiersTextInfo, new RecordItemIndex(144));
            repo.SnapXUntitled.ModifiersText.Click("42;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.FeaturesTextPoint' at 34;7.", repo.SnapXUntitled.FeaturesTextPointInfo, new RecordItemIndex(145));
            repo.SnapXUntitled.FeaturesTextPoint.Click("34;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ValuePoint' at 9;4.", repo.SnapXUntitled.ValuePointInfo, new RecordItemIndex(146));
            repo.SnapXUntitled.ValuePoint.Click("9;4");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Features3' at 48;13.", repo.SnapXUntitled.Features3Info, new RecordItemIndex(147));
            repo.SnapXUntitled.Features3.Click("48;13");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonOK' at 38;8.", repo.SnapXUntitled.ButtonOKInfo, new RecordItemIndex(148));
            repo.SnapXUntitled.ButtonOK.Click("38;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.LocatePoint' at 53;7.", repo.SnapXUntitled.LocatePointInfo, new RecordItemIndex(149));
            repo.SnapXUntitled.LocatePoint.Click("53;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.NominalText' at 33;10.", repo.SnapXUntitled.NominalTextInfo, new RecordItemIndex(150));
            repo.SnapXUntitled.NominalText.Click("33;10");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.UpperText' at 22;6.", repo.SnapXUntitled.UpperTextInfo, new RecordItemIndex(151));
            repo.SnapXUntitled.UpperText.Click("22;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.LowerText' at 23;6.", repo.SnapXUntitled.LowerTextInfo, new RecordItemIndex(152));
            repo.SnapXUntitled.LowerText.Click("23;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.GeometricToleranceText' at 92;9.", repo.SnapXUntitled.GeometricToleranceTextInfo, new RecordItemIndex(153));
            repo.SnapXUntitled.GeometricToleranceText.Click("92;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ANSI' at 27;5.", repo.SnapXUntitled.ANSIInfo, new RecordItemIndex(154));
            repo.SnapXUntitled.ANSI.Click("27;5");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RadioButtonISO' at 33;8.", repo.SnapXUntitled.RadioButtonISOInfo, new RecordItemIndex(155));
            repo.SnapXUntitled.RadioButtonISO.Click("33;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.InputFromStep' at 20;18.", repo.SnapXUntitled.InputFromStepInfo, new RecordItemIndex(156));
            repo.SnapXUntitled.InputFromStep.Click("20;18");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.CheckBoxX' at 25;8.", repo.SnapXUntitled.CheckBoxXInfo, new RecordItemIndex(157));
            repo.SnapXUntitled.CheckBoxX.Click("25;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.CheckBoxY' at 24;5.", repo.SnapXUntitled.CheckBoxYInfo, new RecordItemIndex(158));
            repo.SnapXUntitled.CheckBoxY.Click("24;5");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.InputFromFile' at 84;12.", repo.SnapXUntitled.InputFromFileInfo, new RecordItemIndex(159));
            repo.SnapXUntitled.InputFromFile.Click("84;12");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.KeepFile' at 47;13.", repo.SnapXUntitled.KeepFileInfo, new RecordItemIndex(160));
            repo.SnapXUntitled.KeepFile.Click("47;13");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.DataStream' at 41;8.", repo.SnapXUntitled.DataStreamInfo, new RecordItemIndex(161));
            repo.SnapXUntitled.DataStream.Click("41;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Skip' at 38;8.", repo.SnapXUntitled.SkipInfo, new RecordItemIndex(162));
            repo.SnapXUntitled.Skip.Click("38;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Hide' at 32;8.", repo.SnapXUntitled.HideInfo, new RecordItemIndex(163));
            repo.SnapXUntitled.Hide.Click("32;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonCancel' at 63;9.", repo.SnapXUntitled.ButtonCancelInfo, new RecordItemIndex(164));
            repo.SnapXUntitled.ButtonCancel.Click("63;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Titlebar' at Center.", repo.SnapXUntitled.TitlebarInfo, new RecordItemIndex(165));
            repo.SnapXUntitled.Titlebar.Click();
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(166));
            Keyboard.Press("{LMenu}");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(167));
            Keyboard.Press("c");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'h'.", new RecordItemIndex(168));
            Keyboard.Press("h");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ConstructStepName' at 137;8.", repo.SnapXUntitled.ConstructStepNameInfo, new RecordItemIndex(169));
            repo.SnapXUntitled.ConstructStepName.Click("137;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Expression' at 44;7.", repo.SnapXUntitled.ExpressionInfo, new RecordItemIndex(170));
            repo.SnapXUntitled.Expression.Click("44;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Linear' at 39;9.", repo.SnapXUntitled.LinearInfo, new RecordItemIndex(171));
            repo.SnapXUntitled.Linear.Click("39;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Angular' at 41;11.", repo.SnapXUntitled.AngularInfo, new RecordItemIndex(172));
            repo.SnapXUntitled.Angular.Click("41;11");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ANSI' at 38;15.", repo.SnapXUntitled.ANSIInfo, new RecordItemIndex(173));
            repo.SnapXUntitled.ANSI.Click("38;15");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.RadioButtonISO' at 25;9.", repo.SnapXUntitled.RadioButtonISOInfo, new RecordItemIndex(174));
            repo.SnapXUntitled.RadioButtonISO.Click("25;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.NominalText' at 34;9.", repo.SnapXUntitled.NominalTextInfo, new RecordItemIndex(175));
            repo.SnapXUntitled.NominalText.Click("34;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.UpperText' at 35;7.", repo.SnapXUntitled.UpperTextInfo, new RecordItemIndex(176));
            repo.SnapXUntitled.UpperText.Click("35;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.LowerText' at 29;5.", repo.SnapXUntitled.LowerTextInfo, new RecordItemIndex(177));
            repo.SnapXUntitled.LowerText.Click("29;5");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Skip' at 40;8.", repo.SnapXUntitled.SkipInfo, new RecordItemIndex(178));
            repo.SnapXUntitled.Skip.Click("40;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.AtPosTextMath' at 44;6.", repo.SnapXUntitled.AtPosTextMathInfo, new RecordItemIndex(179));
            repo.SnapXUntitled.AtPosTextMath.Click("44;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonCancel' at 50;13.", repo.SnapXUntitled.ButtonCancelInfo, new RecordItemIndex(180));
            repo.SnapXUntitled.ButtonCancel.Click("50;13");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Titlebar' at Center.", repo.SnapXUntitled.TitlebarInfo, new RecordItemIndex(181));
            repo.SnapXUntitled.Titlebar.Click();
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(182));
            Keyboard.Press("{LMenu}");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(183));
            Keyboard.Press("c");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'r'.", new RecordItemIndex(184));
            Keyboard.Press("r");
            Delay.Milliseconds(0);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ConstructStepName' at 129;9.", repo.SnapXUntitled.ConstructStepNameInfo, new RecordItemIndex(185));
            repo.SnapXUntitled.ConstructStepName.Click("129;9");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Conditions' at 17;8.", repo.SnapXUntitled.ConditionsInfo, new RecordItemIndex(186));
            repo.SnapXUntitled.Conditions.Click("17;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.THENTextBranch' at 14;7.", repo.SnapXUntitled.THENTextBranchInfo, new RecordItemIndex(187));
            repo.SnapXUntitled.THENTextBranch.Click("14;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.GoToStepTextBranch' at 37;7.", repo.SnapXUntitled.GoToStepTextBranchInfo, new RecordItemIndex(188));
            repo.SnapXUntitled.GoToStepTextBranch.Click("37;7");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ELSETextBranch' at 33;4.", repo.SnapXUntitled.ELSETextBranchInfo, new RecordItemIndex(189));
            repo.SnapXUntitled.ELSETextBranch.Click("33;4");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.GoToStepElseBranch' at 33;6.", repo.SnapXUntitled.GoToStepElseBranchInfo, new RecordItemIndex(190));
            repo.SnapXUntitled.GoToStepElseBranch.Click("33;6");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.Skip' at 28;8.", repo.SnapXUntitled.SkipInfo, new RecordItemIndex(191));
            repo.SnapXUntitled.Skip.Click("28;8");
            Delay.Milliseconds(200);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.ButtonCancel' at 59;13.", repo.SnapXUntitled.ButtonCancelInfo, new RecordItemIndex(192));
            repo.SnapXUntitled.ButtonCancel.Click("59;13");
            Delay.Milliseconds(200);

        }

        #region Image Feature Data
        #endregion
    }
#pragma warning restore 0436
}
